Repository gramps-project/gramps, pull requests merged in 2018-02, with the labels that each got.

#542 Fix Geography views for bad 'dbstate.is_open()' test
  gramps/plugins/view/geoclose.py
  gramps/plugins/view/geoevents.py
  gramps/plugins/view/geofamclose.py
  gramps/plugins/view/geofamily.py
  gramps/plugins/view/geoperson.py
  gramps/plugins/view/geoplaces.py
Labels: bug

#545 Some dates are not translated in webcal
  gramps/plugins/webreport/webcal.py
Labels: bug

#368 Implement place formats
  gramps/gen/config.py
  gramps/gen/const.py
  gramps/gen/display/place.py
  gramps/gen/plug/report/stdoptions.py
  gramps/gui/configure.py
  gramps/gui/displaystate.py
  gramps/gui/editors/editplaceformat.py
  gramps/gui/glade/editplaceformat.glade
  gramps/plugins/gramplet/persondetails.py
  gramps/plugins/lib/libpersonview.py
  gramps/plugins/lib/libplaceview.py
  gramps/plugins/textreport/descendreport.py
  gramps/plugins/textreport/detancestralreport.py
  gramps/plugins/textreport/detdescendantreport.py
  gramps/plugins/textreport/familygroup.py
  gramps/plugins/textreport/indivcomplete.py
  gramps/plugins/textreport/placereport.py
  gramps/plugins/textreport/tagreport.py
  gramps/plugins/view/eventview.py
  gramps/plugins/view/pedigreeview.py
  gramps/plugins/view/relview.py
Labels: enhancement

#543 Fix Place Tree view for proper display after filter cleared.
  gramps/gui/filters/sidebar/_placesidebarfilter.py
Labels: bug

#544 Fix character encoding for new tree category reports
  gramps/gen/plug/docgen/treedoc.py
Labels: bug

#547 Apply places changes to the narrativeweb.
  gramps/plugins/webreport/basepage.py
Labels: bug

#549 crash in narrative web if no unused media
  gramps/plugins/webreport/media.py
Labels: bug

#546 Escape special LaTeX characters
  gramps/gen/plug/docgen/treedoc.py
Labels: bug

#550 Update README for Gramps50
  README.md
Labels: Documentation, bug

#553 Fix testsuite failure when build happens out of the source tree.
  gramps/gen/filters/rules/test/person_rules_test.py
Labels: bug

#554 Fix Report Options when used with empty db
  gramps/gui/plug/_guioptions.py
Labels: bug

#555 Privacy problem with the relation to the center person.
  gramps/plugins/webreport/person.py
Labels: bug

#564 Fix ImportError & update API docs year 2018
  docs/conf.py
  docs/gen/gen_db.rst
Labels: bug

#566 Fix Clipboard for right-click on empty clipboard
  gramps/gui/clipboard.py
Labels: bug
