Repository gramps-project/gramps, pull requests merged in 2018-03, with the labels that each got.

#560 Fix multi-page Graph output to pdf with filenames containg spaces
  gramps/gen/plug/docgen/graphdoc.py
Labels: bug

#559 Changed behavior of "Look up with Map Services"
  gramps/plugins/mapservices/googlemap.py
  gramps/plugins/mapservices/openstreetmap.py
Labels: bug

#563 Change BaseSelector so that selection is kept during Find/Clear
  gramps/gui/selectors/baseselector.py
Labels: bug, enhancement

#570 Fix Organize Tags editor for exception on 'x' close
  gramps/gui/views/tags.py
Labels: bug

#571 Fix Fan Chart(s) so they don't crash when opened as last view
  gramps/gui/widgets/fanchart.py
Labels: bug

#565 Fix Book TOC and Index numbering and placement
  gramps/plugins/docgen/cairodoc.py
Labels: bug

#567 [Narrative Web Report]Incorrect heading for stepmother or stepfather
  gramps/plugins/webreport/person.py
Labels: bug

#561 Fix place format option in place report
  gramps/gen/display/place.py
  gramps/gen/plug/report/stdoptions.py
  gramps/plugins/textreport/placereport.py
Labels: Documentation, bug

#557 Fix export gpkg when media files have fractional timestamps.
  gramps/plugins/export/exportpkg.py
Labels: bug

#576 Fix Relationship Graph for extraneous families when using filter
  gramps/plugins/graph/gvrelgraph.py
Labels: bug

#569 Fix up Clipboard for various issues
  gramps/gui/clipboard.py
Labels: bug

#572 Fix Fan charts for scrolling/resizing of window; bad rendering
  gramps/gui/widgets/fanchart.py
  gramps/gui/widgets/fanchart2way.py
  gramps/gui/widgets/fanchartdesc.py
  gramps/plugins/view/fanchart2wayview.py
  gramps/plugins/view/fanchartdescview.py
  gramps/plugins/view/fanchartview.py
Labels: bug

#577 Geography: KML media objects not shown on map.
  gramps/plugins/lib/maps/geography.py
  gramps/plugins/view/geoplaces.py
Labels: bug

#575 Allow Copying of text fields for Details tabs
  gramps/plugins/gramplet/persondetails.py
  gramps/plugins/gramplet/placedetails.py
  gramps/plugins/gramplet/repositorydetails.py
Labels: Documentation, bug, enhancement

#579 Enable copying the birth & death fields for relationship view
  gramps/plugins/view/relview.py
Labels: Documentation, bug, enhancement

#580 Use sgettext for Name Format dialog
  gramps/gen/utils/keyword.py
Labels: bug

#578 Fix places in example.gramps
  example/gramps/example.gramps
Labels: bug, enhancement

#582 [pt_BR]Translation updates and corrections
  po/pt_BR.po
Labels: bug, enhancement

#583 List sort by number for citation confidence level
  gramps/gui/glade/editcitation.glade
  gramps/gui/views/treemodels/citationbasemodel.py
  gramps/gui/views/treemodels/citationlistmodel.py
  gramps/gui/views/treemodels/citationtreemodel.py
Labels: bug

#586 Fix Relationship path between filter for silent fail
  gramps/gen/filters/rules/person/_relationshippathbetween.py
Labels: bug

#587 Fix FTM for delete tree, followed by close; Title etc. shows old tree
  gramps/gui/dbman.py
Labels: bug

#590 Crash when selecting an old note, event, media, ...
  gramps/gui/selectors/baseselector.py
Labels: bug

#591 Enclose tree report image path and file name in braces
  gramps/gen/plug/docgen/treedoc.py
Labels: bug
