Repository gramps-project/gramps, pull requests merged in 2018-09, with the labels that each got.

#643 Fix Find Database Loop Tool (bad import of _collections)
  gramps/plugins/tool/findloop.py
Labels: bug

#644 Fix place reference editor for bad cut/paste on set_latlongitude
  gramps/gui/editors/editplaceref.py
Labels: bug

#652 Fix <ctrl>c in view to get selected item to clipboard
  gramps/gui/views/pageview.py
Labels: bug

#654 Fix Merge Family when same parent is missing from both families
  gramps/gen/merge/mergefamilyquery.py
Labels: bug

#655 Fix corrupted Bookmarks that can happen after Gramps crash
  gramps/gui/views/bookmarks.py
Labels: bug

#649 Fix generate_checksum routine to avoid MemoryError crash
  gramps/gen/utils/file.py
Labels: bug

#651 [WhatsNext gramplet]fix warning
  gramps/plugins/gramplet/whatsnext.py
Labels: bug, work in progress

#648 Fix strings containing deprecated illegal escape sequences
  gramps/gen/config.py
  gramps/gen/datehandler/_date_ar.py
  gramps/gen/datehandler/_date_bg.py
  gramps/gen/datehandler/_date_ca.py
  gramps/gen/datehandler/_date_da.py
  gramps/gen/datehandler/_date_de.py
  gramps/gen/datehandler/_date_el.py
  gramps/gen/datehandler/_date_es.py
  gramps/gen/datehandler/_date_fi.py
  gramps/gen/datehandler/_date_hr.py
  gramps/gen/datehandler/_date_hu.py
  gramps/gen/datehandler/_date_is.py
  gramps/gen/datehandler/_date_it.py
  gramps/gen/datehandler/_date_ja.py
  gramps/gen/datehandler/_date_lt.py
  gramps/gen/datehandler/_date_nb.py
  gramps/gen/datehandler/_date_nl.py
  gramps/gen/datehandler/_date_pl.py
  gramps/gen/datehandler/_date_pt.py
  gramps/gen/datehandler/_date_ru.py
  gramps/gen/datehandler/_date_sk.py
  gramps/gen/datehandler/_date_sl.py
  gramps/gen/datehandler/_date_sr.py
  gramps/gen/datehandler/_date_sv.py
  gramps/gen/datehandler/_date_uk.py
  gramps/gen/datehandler/_date_zh_CN.py
  gramps/gen/datehandler/_date_zh_TW.py
  gramps/gen/datehandler/_dateparser.py
  gramps/gen/display/name.py
  gramps/gen/filters/rules/_changedsincebase.py
  gramps/gen/lib/place.py
  gramps/gen/mime/_winmime.py
  gramps/gen/soundex.py
  gramps/gen/utils/db.py
  gramps/gui/dbman.py
  gramps/gui/editors/editlink.py
  gramps/plugins/docgen/latexdoc.py
  gramps/plugins/docgen/rtfdoc.py
  gramps/plugins/export/test/exportvcard_test.py
  gramps/plugins/importer/importgeneweb.py
  gramps/plugins/importer/importxml.py
  gramps/plugins/importer/test/importvcard_test.py
  gramps/plugins/tool/reorderids.py
  setup.py
  windows/nonAIO/builder/build_GrampsWin32.py
  windows/nonAIO/builder/check_gtk_install.py
  windows/nonAIO/builder/make_launcher.py
  windows/nonAIO/check_gtk_install.py
Labels: bug, enhancement

#656 Speed up Check and Repair, backlinks check stage.
  gramps/plugins/tool/check.py
Labels: bug, enhancement

#657 Fix Check and Repair to deal with bad references empty handle string
  gramps/plugins/test/tools_test.py
  gramps/plugins/tool/check.py
Labels: bug

#653 Fix and restore Statistics Gramplet to 4.2.x status
  gramps/plugins/gramplet/statsgramplet.py
Labels: Documentation, bug, enhancement

#658 [Narrative webreport]Events difficult to read (screen and mobile)
  gramps/plugins/webreport/basepage.py
Labels: bug
