Repository gramps-project/gramps, pull requests merged in 2018-07, with the labels that each got.

#634 Update Debian directory after Gramps 5.0.0-rc1 release.
  debian/changelog
  debian/copyright
  debian/patches/hardcoded_path_person_rules_test.patch
  debian/patches/series
Labels: bug, enhancement

#615 Fix typo in translation
  gramps/plugins/rel/rel_cs.py
Labels: Translation

#614 Fix and update Slovak translation
  po/sk.po
Labels: Translation

#618 Fix dialog button order on non-Mac systems
  gramps/gui/glade/editplace.glade
  gramps/gui/glade/editplaceref.glade
Labels: bug

#612 Export options > Gui alignment issue
  gramps/gui/plug/export/_exportoptions.py
Labels: bug

#631 Fix BaseSelector to avoid long delay before display on large trees
  gramps/gui/glade/baseselector.glade
  gramps/gui/selectors/baseselector.py
Labels: bug

#633 Correct binary test logic for primary mask.
  gramps/gui/clipboard.py
  gramps/gui/editors/displaytabs/buttontab.py
  gramps/gui/editors/displaytabs/surnametab.py
  gramps/gui/filters/_searchbar.py
  gramps/gui/filters/sidebar/_sidebarfilter.py
  gramps/gui/utils.py
  gramps/gui/views/navigationview.py
  gramps/gui/widgets/grampletpane.py
  gramps/gui/widgets/interactivesearchbox.py
  gramps/gui/widgets/multitreeview.py
  gramps/gui/widgets/styledtexteditor.py
Labels: bug
