Repository gramps-project/gramps, pull requests merged in 2018-12, with the labels that each got.

#690 Fix Russian date handler crash when Russian .po (actually .mo) isn't present
  gramps/gen/datehandler/_date_ru.py
Labels: bug

#712 Fix dbapi set_name_group_mapping to properly close transaction
  gramps/plugins/db/dbapi/dbapi.py
Labels: bug

#731 Fix Rebuild Secondary Indexes tool for dbapi backends
  gramps/plugins/db/dbapi/dbapi.py
  gramps/plugins/tool/rebuild.py
Labels: bug

#734 Allow addon Reports to specify a help button URL for options dialog
  gramps/gui/plug/report/_reportdialog.py
Labels: bug

#740 Google maps URL problem
  gramps/plugins/mapservices/googlemap.py
Labels: bug

#742 Fix contents of enclosed_by secondary dbapi column
  gramps/gen/db/generic.py
Labels: bug

#741 Croatian localisation updates
  gramps/gen/datehandler/_date_hr.py
  po/hr.po
Labels: Translation

#738 Help issues for bug 9042
  gramps/gui/configure.py
  gramps/gui/display.py
  gramps/gui/glade/book.glade
  gramps/gui/glade/styleeditor.glade
  gramps/gui/plug/report/_bookdialog.py
  gramps/gui/plug/report/_styleeditor.py
  gramps/gui/selectors/selectperson.py
  gramps/gui/selectors/selectrepository.py
  gramps/gui/widgets/grampletpane.py
  gramps/gui/widgets/reorderfam.py
  gramps/plugins/tool/mediamanager.py
  gramps/plugins/tool/relcalc.glade
  gramps/plugins/tool/relcalc.py
  po/ar.po
  po/bg.po
  po/br.po
  po/ca.po
  po/cs.po
  po/da.po
  po/de.po
  po/el.po
  po/en_GB.po
  po/eo.po
  po/es.po
  po/fi.po
  po/fr.po
  po/ga.po
  po/gramps.pot
  po/he.po
  po/hr.po
  po/hu.po
  po/is.po
  po/it.po
  po/ja.po
  po/lt.po
  po/mk.po
  po/nb.po
  po/nl.po
  po/nn.po
  po/pl.po
  po/pt_BR.po
  po/pt_PT.po
  po/ro.po
  po/ru.po
  po/sk.po
  po/sl.po
  po/sq.po
  po/sr.po
  po/sr_Latn.po
  po/sv.po
  po/ta.po
  po/tr.po
  po/uk.po
  po/vi.po
  po/zh_CN.po
  po/zh_HK.po
  po/zh_TW.po
Labels: Documentation, bug

#745 Set correct font resolution for Mac when drawing text directly to cairo.
  gramps/gui/widgets/fanchart.py
  gramps/plugins/docgen/cairodoc.py
  gramps/plugins/lib/maps/messagelayer.py
  gramps/plugins/view/pedigreeview.py
Labels: bug

#747 Avoid leading and trailing spaces when copy/paste
  gramps/gui/editors/editplace.py
  gramps/gui/editors/editplaceref.py
Labels: bug

#748 German translation corrections
  po/de.po
Labels: Translation
