Repository gramps-project/gramps, pull requests merged in 2018-10, with the labels that each got.

#613 Fix bsddb for person sort with empty Surname list
  gramps/plugins/db/bsddb/read.py
Labels: bug

#665 Better typography in graph reports
  gramps/plugins/graph/gvfamilylines.py
  gramps/plugins/graph/gvhourglass.py
  gramps/plugins/graph/gvrelgraph.py
Labels: enhancement

#645 fix view so column widths are preserved when using filters
  gramps/gui/columnorder.py
  gramps/gui/views/listview.py
Labels: bug

#617 Do not use hyphen for living persons in hourglass graph
  gramps/plugins/graph/gvhourglass.py
Labels: Documentation, enhancement

#639 Replace rounded corners checkbox by dropdown.
  gramps/plugins/graph/gvfamilylines.py
Labels: Documentation, enhancement

#663 RelGraphReport: Add an option to omit "irrelevant" family nodes
  gramps/plugins/graph/gvrelgraph.py
Labels: Documentation, enhancement

#674 In personsidebarfilter, search on each part of name
  gramps/gui/filters/sidebar/_personsidebarfilter.py
Labels: enhancement

#668 NarrativeWeb: space between place, description and
  data/css/Web_Basic-Ash.css
  data/css/Web_Basic-Blue.css
  data/css/Web_Basic-Cypress.css
  data/css/Web_Basic-Lilac.css
  data/css/Web_Basic-Peach.css
  data/css/Web_Basic-Spruce.css
  data/css/Web_Horizontal-Menus.css
  data/css/Web_Mainz.css
  data/css/Web_Nebraska.css
  gramps/plugins/webreport/basepage.py
Labels: bug
