Repository gramps-project/gramps, pull requests merged in 2019-01, with the labels that each got.

#752 Fix Media editor when using double click the preview of added media
  gramps/gui/editors/editmedia.py
Labels: bug

#750 Remember location of Sort Events Tool
  gramps/plugins/tool/sortevents.py
Labels: bug, enhancement

#548 Add Buchheim tree ancestor trees to Narrated Web Report
  gramps/plugins/webreport/buchheim.py
  gramps/plugins/webreport/layout.py
  gramps/plugins/webreport/media.py
  gramps/plugins/webreport/narrativeweb.py
  gramps/plugins/webreport/person.py
  po/POTFILES.in
  test/AncestorTree/AncestorTree.gramps
Labels: Documentation, enhancement

#678 Fix Delete dialogs to all canceling multiple deletes more easily
  gramps/gui/dialog.py
  gramps/gui/glade/dialog.glade
  gramps/gui/views/listview.py
Labels: enhancement

#682 NarrativeWeb: add enclosed by and encloses (place)
  gramps/plugins/webreport/basepage.py
Labels: enhancement

#683 Geography places: add color for custom places name
  gramps/plugins/view/geoplaces.py
Labels: enhancement

#686 Replace eval with getattr when loading plugin classes
  gramps/cli/arghandler.py
  gramps/gen/plug/report/_book.py
  gramps/gen/relationship.py
  gramps/gui/plug/_dialogs.py
  gramps/gui/plug/quick/_quickreports.py
  gramps/plugins/lib/libplaceview.py
Labels: Code Quality

#497 Filter fixes to prevent MatchesFilter types from running multiple times
  gramps/gen/filters/rules/person/_deeprelationshippathbetween.py
  gramps/gen/filters/rules/person/_hascommonancestorwithfiltermatch.py
  gramps/gen/filters/rules/person/_isancestoroffiltermatch.py
  gramps/gen/filters/rules/person/_ischildoffiltermatch.py
  gramps/gen/filters/rules/person/_isdescendantfamilyoffiltermatch.py
  gramps/gen/filters/rules/person/_isdescendantoffiltermatch.py
  gramps/gen/filters/rules/person/_isparentoffiltermatch.py
  gramps/gen/filters/rules/person/_issiblingoffiltermatch.py
Labels: enhancement

#499 Filters optimization; Use cache proxy with filters in views
  gramps/gui/views/treemodels/flatbasemodel.py
  gramps/gui/views/treemodels/treebasemodel.py
Labels: enhancement

#701 Filter Rule editor, save pane position
  gramps/gui/editors/filtereditor.py
Labels: enhancement

#711 Add option to hide empty information on statistics chart
  gramps/plugins/drawreport/statisticschart.py
Labels: enhancement

#753 Corrections in 'Tip of Day'; changed 'Schlussnotizen' to 'Quellennach…
  po/de.po
Labels: Translation

#763 Not all place types appears on family lines Graph
  gramps/plugins/graph/gvfamilylines.py
Labels: bug, enhancement

#766 fix Place Format Editor file save/load for difficult names
  gramps/gen/display/place.py
Labels: bug

#767 [German] Change Text on Settings -> Colour
  po/de.po
Labels: Translation

#769 Fix Relationship Graph; extra people when using filters & subgraphs
  gramps/plugins/graph/gvrelgraph.py
Labels: bug

#770 We should stay on the selected item in list views:
  gramps/gen/merge/mergefamilyquery.py
  gramps/gui/merge/mergecitation.py
  gramps/gui/merge/mergeevent.py
  gramps/gui/merge/mergefamily.py
  gramps/gui/merge/mergemedia.py
  gramps/gui/merge/mergenote.py
  gramps/gui/merge/mergeperson.py
  gramps/gui/merge/mergeplace.py
  gramps/gui/merge/mergerepository.py
  gramps/gui/merge/mergesource.py
  gramps/plugins/test/db_undo_and_signals_test.py
Labels: bug

#771 Fix Name editor crash after clearing a group_as name on dbapi dbs
  gramps/plugins/db/dbapi/dbapi.py
Labels: bug

#773 Fix Descendent Tree report for crash when person has multiple
  gramps/plugins/drawreport/descendtree.py
Labels: bug
