Repository gramps-project/gramps, pull requests merged in 2019-05, with the labels that each got.

#735 Add first class support for Occupation attribute
  gramps/gen/lib/attrtype.py
  gramps/gen/plug/docgen/treedoc.py
Labels: enhancement

#737 vCalendar: Convenient display on mobile devices.
  gramps/plugins/export/exportvcalendar.py
Labels: enhancement

#746 Fix AppStream metadata validation
  data/gramps.appdata.xml.in
Labels: Documentation, bug

#757 Adjust - Polish translation
  po/pl.po
Labels: Translation

#758 Replace _2BUTTON_PRESS by DOUBLE_BUTTON_PRESS
  gramps/gui/clipboard.py
  gramps/gui/dbman.py
  gramps/gui/editors/displaytabs/buttontab.py
  gramps/gui/editors/displaytabs/gallerytab.py
  gramps/gui/editors/editmedia.py
  gramps/gui/editors/editmediaref.py
  gramps/gui/editors/editperson.py
  gramps/gui/editors/filtereditor.py
  gramps/gui/listmodel.py
  gramps/gui/plug/_windows.py
  gramps/gui/plug/report/_bookdialog.py
  gramps/gui/plug/report/_styleeditor.py
  gramps/gui/views/listview.py
  gramps/gui/widgets/grampletpane.py
  gramps/gui/widgets/photo.py
  gramps/plugins/gramplet/leak.py
  gramps/plugins/tool/removeunused.py
  gramps/plugins/tool/verify.py
  gramps/plugins/view/pedigreeview.py
Labels: Code Quality

#759 Allow _T_ as a valid function name
  .pylintrc
Labels: Code Quality

#760 Remove extraneous whitespace before colon
  gramps/gen/datehandler/_dateutils.py
  gramps/gen/filters/rules/event/_matchespersonfilter.py
  gramps/gen/filters/rules/place/_hasnolatorlon.py
  gramps/gen/filters/rules/place/_inlatlonneighborhood.py
  gramps/gen/utils/maclocale.py
  gramps/gui/editors/editprimary.py
  gramps/gui/plug/export/_exportassistant.py
  gramps/gui/widgets/styledtexteditor.py
  gramps/plugins/importer/importxml.py
  gramps/plugins/lib/libcairodoc.py
  gramps/plugins/quickview/all_events.py
  gramps/plugins/quickview/all_relations.py
  gramps/plugins/quickview/lineage.py
  gramps/plugins/rel/rel_ca.py
  gramps/plugins/tool/notrelated.py
Labels: Code Quality

#796 Use theme settings for the error state of entry widgets
  gramps/gui/widgets/validatedmaskedentry.py
Labels: Documentation, bug, enhancement

#749 extrapage can now point to joomla, drupal, ...
  gramps/plugins/webreport/basepage.py
Labels: enhancement

#756 changed 'Edit ->Set Home Person' to 'Edit -> Set Home Person'
  gramps/gui/views/navigationview.py
  po/ar.po
  po/bg.po
  po/br.po
  po/ca.po
  po/cs.po
  po/da.po
  po/de.po
  po/el.po
  po/en_GB.po
  po/eo.po
  po/es.po
  po/fi.po
  po/fr.po
  po/ga.po
  po/gramps.pot
  po/he.po
  po/hr.po
  po/hu.po
  po/is.po
  po/it.po
  po/ja.po
  po/lt.po
  po/mk.po
  po/nb.po
  po/nl.po
  po/nn.po
  po/pl.po
  po/pt_BR.po
  po/pt_PT.po
  po/ro.po
  po/ru.po
  po/sk.po
  po/sl.po
  po/sq.po
  po/sr.po
  po/sr_Latn.po
  po/sv.po
  po/ta.po
  po/tr.po
  po/uk.po
  po/vi.po
  po/zh_CN.po
  po/zh_HK.po
  po/zh_TW.po
Labels: Documentation, Translation

#768 Add tooltip for Gramplet Bar
  gramps/gui/widgets/grampletbar.py
Labels: Documentation, bug, enhancement

#778 On restart after crash, offer to run Check & Repair
  gramps/gen/config.py
  gramps/grampsapp.py
  gramps/gui/viewmanager.py
Labels: Documentation, enhancement

#781 Add buttons for arrangement of GalleryTab media order
  gramps/gui/editors/displaytabs/buttontab.py
  gramps/gui/editors/displaytabs/gallerytab.py
Labels: Documentation, enhancement

#805 Fix typo in Slovak translation
  po/sk.po
Labels: Translation

#802 Webcal: add death anniversary
  gramps/plugins/webreport/webcal.py
Labels: enhancement

#671 Add Ahnentafel option on hourglass
  gramps/gen/plug/docgen/graphdoc.py
  gramps/plugins/graph/gvhourglass.py
Labels: enhancement

#775 Config dialog [master]
  gramps/gen/config.py
  gramps/gui/configure.py
  gramps/gui/utils.py
Labels: Code Quality, enhancement

#598 Geps/gep 039 genealogical symbols
  gramps/gen/config.py
  gramps/gen/utils/libformatting.py
  gramps/gen/utils/symbols.py
  gramps/gui/configure.py
  gramps/gui/displaystate.py
  gramps/gui/viewmanager.py
  gramps/gui/views/pageview.py
  gramps/gui/widgets/fanchart.py
  gramps/plugins/lib/maps/datelayer.py
  gramps/plugins/lib/maps/geography.py
  gramps/plugins/lib/maps/messagelayer.py
  gramps/plugins/view/fanchart2wayview.py
  gramps/plugins/view/fanchartdescview.py
  gramps/plugins/view/fanchartview.py
  gramps/plugins/view/geoclose.py
  gramps/plugins/view/geoevents.py
  gramps/plugins/view/geofamclose.py
  gramps/plugins/view/geofamily.py
  gramps/plugins/view/geomoves.py
  gramps/plugins/view/geoperson.py
  gramps/plugins/view/pedigreeview.py
  gramps/plugins/view/relview.py
Labels: enhancement

#774 Have a better narrative web site
  data/css/Web_Basic-Ash.css
  data/css/Web_Basic-Blue.css
  data/css/Web_Basic-Cypress.css
  data/css/Web_Basic-Lilac.css
  data/css/Web_Basic-Peach.css
  data/css/Web_Basic-Spruce.css
  data/css/Web_Mainz.css
  data/css/Web_Nebraska.css
  gramps/plugins/webreport/addressbook.py
  gramps/plugins/webreport/addressbooklist.py
  gramps/plugins/webreport/basepage.py
  gramps/plugins/webreport/citation.py
  gramps/plugins/webreport/common.py
  gramps/plugins/webreport/contact.py
  gramps/plugins/webreport/download.py
  gramps/plugins/webreport/event.py
  gramps/plugins/webreport/family.py
  gramps/plugins/webreport/home.py
  gramps/plugins/webreport/introduction.py
  gramps/plugins/webreport/layout.py
  gramps/plugins/webreport/media.py
  gramps/plugins/webreport/narrativeweb.py
  gramps/plugins/webreport/person.py
  gramps/plugins/webreport/place.py
  gramps/plugins/webreport/repository.py
  gramps/plugins/webreport/source.py
  gramps/plugins/webreport/statistics.py
  gramps/plugins/webreport/surname.py
  gramps/plugins/webreport/surnamelist.py
  gramps/plugins/webreport/thumbnail.py
  gramps/plugins/webstuff/webstuff.py
Labels: enhancement

#733 Relationship Graph: Father and Mother are connected by an invisible line.
  gramps/plugins/graph/gvrelgraph.py
Labels: enhancement

#789 Bump required Python version to 3.3
  gramps/grampsapp.py
Labels: enhancement

#787 Fix PythonDeprecationWarning for collections.abc
  gramps/gen/filters/_filterlist.py
  gramps/gen/updatecallback.py
  gramps/gui/configure.py
  gramps/gui/makefilter.py
  gramps/gui/plug/quick/_quickreports.py
  gramps/plugins/export/exportcsv.py
  gramps/plugins/export/exportftree.py
  gramps/plugins/export/exportgeneweb.py
  gramps/plugins/export/exportvcalendar.py
  gramps/plugins/export/exportvcard.py
  gramps/plugins/importer/importxml.py
Labels: Code Quality

#788 Fix Python time.clock deprecation
  gramps/gen/filters/rules/test/person_rules_test.py
  gramps/gui/views/listview.py
  gramps/gui/views/treemodels/flatbasemodel.py
  gramps/gui/views/treemodels/treebasemodel.py
Labels: Code Quality

#810 Add occupation & residence events + attributes in the CSV persons importer
  gramps/plugins/importer/importcsv.py
Labels: Documentation, enhancement

#783 New tool to suppress leading and trailing spaces.
  gramps/plugins/tool/removespaces.glade
  gramps/plugins/tool/removespaces.py
  gramps/plugins/tool/tools.gpr.py
Labels: Documentation, enhancement

#813 Add option to show the Gramps ID in parenthesis in the fan chart
  gramps/gui/widgets/fanchart.py
  gramps/gui/widgets/fanchart2way.py
  gramps/gui/widgets/fanchartdesc.py
  gramps/plugins/gramplet/fanchart2waygramplet.py
  gramps/plugins/gramplet/fanchartdescgramplet.py
  gramps/plugins/gramplet/fanchartgramplet.py
  gramps/plugins/view/fanchart2wayview.py
  gramps/plugins/view/fanchartdescview.py
  gramps/plugins/view/fanchartview.py
Labels: enhancement

#815 Add a mailto choice to Internet Address
  gramps/gui/editors/editlink.py
Labels: enhancement

#817 Allow an option to not use hexagons for unknown gender
  gramps/plugins/graph/gvrelgraph.py
Labels: enhancement
