Repository gramps-project/gramps, pull requests merged in 2019-06, with the labels that each got.

#819 Fix '_havechildren.py' person filter
  gramps/gen/filters/rules/person/_havechildren.py
  gramps/gen/filters/rules/test/person_rules_test.py
Labels: bug

#818 Correct English translation strings for unmarried partners
  gramps/gen/relationship.py
  po/ar.po
  po/bg.po
  po/br.po
  po/ca.po
  po/cs.po
  po/da.po
  po/de.po
  po/el.po
  po/en_GB.po
  po/eo.po
  po/es.po
  po/fi.po
  po/fr.po
  po/ga.po
  po/he.po
  po/hr.po
  po/hu.po
  po/is.po
  po/it.po
  po/ja.po
  po/lt.po
  po/mk.po
  po/nb.po
  po/nl.po
  po/nn.po
  po/pl.po
  po/pt_BR.po
  po/pt_PT.po
  po/ro.po
  po/ru.po
  po/sk.po
  po/sl.po
  po/sq.po
  po/sr.po
  po/sr_Latn.po
  po/sv.po
  po/ta.po
  po/tr.po
  po/uk.po
  po/vi.po
  po/zh_CN.po
  po/zh_HK.po
  po/zh_TW.po
Labels: Documentation, bug

#816 Fix uimanager, menu translations
  gramps/gui/uimanager.py
Labels: bug

#814 Fix crash for multiple deletes in one transaction
  gramps/gui/displaystate.py
  gramps/gui/views/listview.py
Labels: bug

#820 Fix '_hasattributebase.py'
  gramps/gen/filters/rules/_hasattributebase.py
Labels: bug

#824 Update Croatian translation
  po/hr.po
Labels: Translation

#811 Avoid invalid characters in the entry fields
  gramps/gui/editors/displaytabs/surnametab.py
  gramps/gui/widgets/monitoredwidgets.py
Labels: bug

#812 Avoid comma in a lat/lon entry field.
  gramps/gen/utils/place.py
  gramps/gen/utils/test/place_test.py
  gramps/plugins/view/geoplaces.py
Labels: bug

#823 Fix metadataviewer.py
  gramps/plugins/gramplet/metadataviewer.py
Labels: bug

#822 Fix CLI import so that different db types can be used
  gramps/cli/arghandler.py
Labels: bug
