Repository gramps-project/gramps, pull requests merged in 2019-09, with the labels that each got.

#877 Make the narratives notes placement an option.
  gramps/plugins/webreport/narrativeweb.py
  gramps/plugins/webreport/person.py
Labels: Documentation, bug, regression

#878 Error when checking option to add Quit to Taskbar
  gramps/gui/configure.py
  gramps/gui/widgets/grampletbar.py
Labels: bug

#879 Translation problem when creating event filter
  gramps/gui/autocomp.py
Labels: bug

#881 Fix bug in web connection menu launching incorrect web site
  gramps/gui/plug/quick/_quickreports.py
Labels: bug

#882 Restore keybindings for gramplet bars
  gramps/gui/views/pageview.py
Labels: bug

#883 Fix exception when editing Note with italics/bold etc. in non English
  gramps/gui/widgets/styledtexteditor.py
Labels: bug

#884 Genealogical symbols : Some corrections
  gramps/plugins/view/relview.py
Labels: bug

#885 Narrative web: Mainz Style sheet weird looking
  data/css/Web_Mainz.css
Labels: bug

#886 The Clean Input Data tool failed to find en dash
  gramps/plugins/tool/removespaces.py
Labels: bug

#887 Cursor position error in lat and long fields
  gramps/gui/widgets/validatedmaskedentry.py
Labels: bug

#888 Fix missing menus/buttons when operating in non-English languages
  gramps/gui/uimanager.py
  gramps/gui/views/tags.py
Labels: bug

#889 Fix to make Gtk 'action names' always valid.
  gramps/gen/plug/_pluginreg.py
  gramps/gui/managedwindow.py
  gramps/gui/plug/quick/_quickreports.py
  gramps/gui/uimanager.py
  gramps/gui/viewmanager.py
  gramps/gui/views/tags.py
  gramps/gui/widgets/grampletpane.py
Labels: bug

#891 Fix Graph outputs for multiple page PDF Postscript
  gramps/gen/plug/docgen/graphdoc.py
Labels: bug

#874 Could not convert string to float
  gramps/gen/filters/rules/place/_withinarea.py
Labels: bug

#892 Fix missing tooltip translations in the Note editor toolbar
  gramps/gui/widgets/styledtexteditor.py
Labels: bug

#828 Update croatian hr.po file
  po/hr.po
Labels: Translation, work in progress

#846 Update Portuguese (Europe) translation
  po/pt_PT.po
Labels: Translation

#893 Fix Statusbar HandleError on merge families
  gramps/gui/views/listview.py
Labels: bug

#894 Fix CLI crash when generating reports
  gramps/cli/grampscli.py
Labels: bug

#895 Remove reload_custom_filters to conform to PR894
  gramps/plugins/webreport/narrativeweb.py
Labels: bug

#896 Fix odt output when db owner has XML unfriendly chars ('&')
  gramps/plugins/docgen/odfdoc.py
Labels: bug

#898 Update French translation
  po/fr.po
Labels: Translation

#900 Using regex in the sidebar gives different result
  gramps/gui/filters/sidebar/_personsidebarfilter.py
Labels: bug, regression

#909 [Debian ( .deb file)]Release511 updates
  debian/changelog
  debian/control
Labels: bug

#907 Fix 'Go' menu direct object selection, goes to wrong place
  gramps/gui/views/navigationview.py
Labels: bug
