Repository gramps-project/gramps, pull requests merged in 2019-10, with the labels that each got.

#906 Escape for name, dates and places in graph reports
  gramps/plugins/graph/gvfamilylines.py
  gramps/plugins/graph/gvhourglass.py
  gramps/plugins/graph/gvrelgraph.py
Labels: bug

#911 Fix Preferences so <ctrl>PageUp/PageDn doesn't stick on Dates tab
  gramps/gui/configure.py
Labels: Documentation, bug

#912 WEBCAL: Wrong web calendar title on home page
  gramps/plugins/webreport/webcal.py
Labels: bug

#914 Narrativeweb: Mainz problem with the homepage and
  data/css/Web_Mainz.css
Labels: bug

#821 Add 'HasAttribute' filter rule to citations, repositories and sources
  gramps/gen/filters/rules/citation/__init__.py
  gramps/gen/filters/rules/citation/_hasattribute.py
  gramps/gen/filters/rules/repository/__init__.py
  gramps/gen/filters/rules/repository/_hasattribute.py
  gramps/gen/filters/rules/source/__init__.py
  gramps/gen/filters/rules/source/_hasattribute.py
  po/POTFILES.in
Labels: Documentation, enhancement

#832 Remove tag from selected rows
  gramps/gui/views/tags.py
  gramps/plugins/lib/libpersonview.py
  gramps/plugins/lib/libplaceview.py
  gramps/plugins/view/citationlistview.py
  gramps/plugins/view/citationtreeview.py
  gramps/plugins/view/eventview.py
  gramps/plugins/view/familyview.py
  gramps/plugins/view/mediaview.py
  gramps/plugins/view/noteview.py
  gramps/plugins/view/repoview.py
  gramps/plugins/view/sourceview.py
Labels: Documentation, enhancement

#848 Add date format option for 'numeric date with leading zeros'
  gramps/gen/datehandler/_date_de.py
Labels: enhancement

#851 Add a new person filter rule 'HasAddressText'
  gramps/gen/filters/rules/person/__init__.py
  gramps/gen/filters/rules/person/_hasaddresstext.py
  po/POTFILES.in
Labels: enhancement

#902 Add new output format to the tree document generator
  gramps/gen/plug/docgen/treedoc.py
Labels: Documentation, enhancement

#904 Better code quality for within area rule
  gramps/gen/filters/rules/place/_withinarea.py
Labels: Code Quality

#910 Reorder ID tool fixes
  gramps/plugins/tool/reorderids.py
Labels: bug

#925 Fix Descendat Tree report for HandleError when no parents on family
  gramps/plugins/drawreport/descendtree.py
Labels: bug

#927 Fix CLI parser to accept negative integers as valid
  gramps/cli/plug/__init__.py
Labels: bug

#928 Fix improper escaping in odt output for TOC/Bookmark etc.
  gramps/plugins/docgen/odfdoc.py
Labels: bug

#921 Patch for PedigreeView not reflecting changes to birthday or death
  gramps/plugins/view/pedigreeview.py
Labels: bug

#916 NarrativeWeb: dates not localised in place pages
  gramps/plugins/webreport/basepage.py
  gramps/plugins/webreport/narrativeweb.py
  gramps/plugins/webreport/webcal.py
Labels: bug

#923 Fix Gramps -v error when Gtk is not present
  gramps/grampsapp.py
Labels: bug

#915 Fix tag colors on PedigreeView
  gramps/gui/utils.py
  gramps/plugins/view/pedigreeview.py
Labels: bug

#929 Narrative web: Ancestor's tree display looks weird
  data/css/ancestortree.css
  gramps/plugins/webreport/buchheim.py
  gramps/plugins/webreport/person.py
Labels: bug

#918 Update POTFILES.in/skip for missing translations
  po/POTFILES.in
  po/POTFILES.skip
Labels: bug

#933 Update translation template due to pr #918
  po/gramps.pot
Labels: Translation

#920 Fix various Entry fields so Undo/Redo works
  gramps/gui/widgets/monitoredwidgets.py
  gramps/gui/widgets/undoableentry.py
Labels: bug

#934 Update croatian hr.po
  po/hr.po
Labels: Translation

#930 Fix Preferences/Genealogical Symbols when only one font is present that passes
  gramps/gui/configure.py
Labels: bug

#932 Fix Window family tree title for non-ASCII chars on Windows
  gramps/cli/grampscli.py
  gramps/gen/db/generic.py
Labels: bug

#939 Update Hebrew translation
  po/he.po
Labels: Translation

#943 Fix Spanish translation for dates
  po/es.po
Labels: Translation, bug

#940 Fix the Preferences 'Age display precision' value getting lost
  gramps/gui/configure.py
Labels: bug

#936 Limit Age Stats gramplet settings to appropriate values
  gramps/plugins/gramplet/agestats.py
Labels: bug
