Repository gramps-project/gramps, pull requests merged in 2019-12, with the labels that each got.

#963 [Tree doc Tex] typo on custom size
  gramps/gen/plug/docgen/treedoc.py
Labels: bug

#917 WEBCAL: Trying to have a better web calendar
  data/css/Web_Basic-Ash.css
  data/css/Web_Basic-Blue.css
  data/css/Web_Basic-Cypress.css
  data/css/Web_Basic-Lilac.css
  data/css/Web_Basic-Peach.css
  data/css/Web_Basic-Spruce.css
  data/css/Web_Mainz.css
  data/css/Web_Nebraska.css
  data/css/Web_Print-Default.css
  data/css/Web_Visually.css
  gramps/plugins/webreport/webcal.py
Labels: enhancement

#961 [Tree doc Tex] fix "-" char on place name
  gramps/gen/plug/docgen/treedoc.py
Labels: bug

#956 fix tagref support
  gramps/gen/proxy/private.py
Labels: bug

#931 Narrative web: Some improvements
  data/css/Web_Basic-Ash.css
  data/css/Web_Basic-Blue.css
  data/css/Web_Basic-Cypress.css
  data/css/Web_Basic-Lilac.css
  data/css/Web_Basic-Peach.css
  data/css/Web_Basic-Spruce.css
  data/css/Web_Citations-Outline.css
  data/css/Web_DropDown-Menus.css
  data/css/Web_Fade-Menus.css
  data/css/Web_Horizontal-Menus.css
  data/css/Web_Mainz.css
  data/css/Web_Nebraska.css
  data/css/Web_Print-Default.css
  data/css/Web_Vertical-Menus.css
  data/css/Web_Visually.css
  data/css/ancestortree.css
  data/css/narrative-maps.css
  gramps/plugins/webreport/basepage.py
  gramps/plugins/webreport/common.py
  gramps/plugins/webreport/event.py
  gramps/plugins/webreport/family.py
  gramps/plugins/webreport/media.py
  gramps/plugins/webreport/narrativeweb.py
  gramps/plugins/webreport/person.py
  gramps/plugins/webreport/place.py
  gramps/plugins/webreport/repository.py
  gramps/plugins/webreport/source.py
  gramps/plugins/webreport/thumbnail.py
  gramps/plugins/webreport/updates.py
Labels: Documentation, enhancement

#905 Add tooltips for places in clean input data tool
  gramps/plugins/tool/removespaces.py
Labels: enhancement

#842 Narrative web: New features
  data/css/Web_Basic-Peach.css
  data/css/narrative-maps.css
  gramps/plugins/webreport/common.py
  gramps/plugins/webreport/person.py
  gramps/plugins/webreport/place.py
Labels: Documentation, enhancement

#968 Fixes bug ID 0011470: some date variants in CS language are not consider valid
  gramps/gen/datehandler/_date_cs.py
Labels: Translation
