Repository gramps-project/gramps, pull requests merged in 2019-07, with the labels that each got.

#831 Fix duplicated accelerators
  gramps/gui/viewmanager.py
  gramps/plugins/lib/maps/geography.py
  gramps/plugins/view/fanchart2wayview.py
  gramps/plugins/view/fanchartdescview.py
  gramps/plugins/view/fanchartview.py
  gramps/plugins/view/geoclose.py
  gramps/plugins/view/geoevents.py
  gramps/plugins/view/geofamclose.py
  gramps/plugins/view/geofamily.py
  gramps/plugins/view/geomoves.py
  gramps/plugins/view/geoperson.py
  gramps/plugins/view/geoplaces.py
Labels: Documentation, bug, enhancement

#829 OSM forward all http resquest to https.
  gramps/plugins/webreport/person.py
  gramps/plugins/webreport/place.py
Labels: bug

#830 Geography: pins very big when related to 2 places
  gramps/plugins/lib/maps/markerlayer.py
Labels: bug

#845 Update hu translation
  po/hu.po
Labels: Translation

#835 Fix zoom via mouse wheel in media event editor selectionwidget
  gramps/gui/widgets/selectionwidget.py
Labels: bug

#836 Fix crash when addon/plugin contains an id with space
  gramps/gui/managedwindow.py
Labels: bug

#847 Fix dbapi reindex_reference_maps tool to properly close transaction
  gramps/plugins/db/dbapi/dbapi.py
Labels: bug

#849 Fix graphs on Windows for font selection not working
  gramps/gen/config.py
  gramps/gen/plug/docgen/graphdoc.py
  gramps/grampsapp.py
  gramps/gui/configure.py
Labels: bug

#850 Fix graphs on Windows for font selection not working
  gramps/gen/config.py
  gramps/gen/plug/docgen/graphdoc.py
  gramps/grampsapp.py
  gramps/gui/configure.py
Labels: bug

#844 Fix Preferences dialog so General tab appears first, not Symbols
  gramps/gui/configure.py
Labels: bug

#852 Fix AncestorTree so add siblings to center person works
  gramps/plugins/drawreport/ancestortree.py
  gramps/plugins/lib/librecurse.py
Labels: bug

#858 fix crash when using sidebar filter and merging in another view
  gramps/gui/views/treemodels/flatbasemodel.py
Labels: bug
