Repository gramps-project/gramps, pull requests merged in 2020-05, with the labels that each got.

#1036 Narweb: Description message is not translatable
  gramps/plugins/webreport/updates.py
Labels: enhancement

#1037 Narweb: incorrect place index if alternate names
  gramps/plugins/webreport/basepage.py
  gramps/plugins/webreport/common.py
  gramps/plugins/webreport/narrativeweb.py
  gramps/plugins/webreport/place.py
Labels: enhancement, work in progress

#1013 Fix GrampsType for comparison bug with empty string as one value
  gramps/gen/lib/grampstype.py
Labels: bug

#1020 Fix dbapi to support "Abandon Changes & Quit" feature
  gramps/gen/db/generic.py
  gramps/plugins/db/dbapi/dbapi.py
Labels: bug

#1022 Fix Windows GUI mode startup for crash with some languages
  gramps/grampsapp.py
Labels: bug

#1026 Fix Dashboard Gramplets to update during db close when not shown
  gramps/gui/viewmanager.py
Labels: bug

#1028 Suppress age = 0 days in events list
  gramps/gui/editors/displaytabs/eventrefmodel.py
  gramps/plugins/gramplet/events.py
Labels: bug

#1030 Fix some Python syntax errors that appear in v3.8.x
  gramps/gen/plug/_manager.py
  gramps/gen/plug/_pluginreg.py
  gramps/gui/pluginmanager.py
  gramps/plugins/lib/maps/messagelayer.py
Labels: bug

#1031 Fix RemoveUnused tool for crash caused by PyGObject problem
  gramps/plugins/tool/removeunused.py
Labels: bug

#1035 Fix GEDCOM import for bad source title when sources precede references.
  gramps/plugins/lib/libgedcom.py
Labels: bug

#1039 Add uistate to tree views filter initialization
  gramps/gui/views/treemodels/treebasemodel.py
Labels: bug

#1041 Allow filter rules to access Family filters
  gramps/gui/editors/filtereditor.py
Labels: enhancement
