Repository gramps-project/gramps, pull requests merged in 2020-01, with the labels that each got.

#978 Fix Dashboard for adding Gramplet crash in Slovenian
  gramps/gui/widgets/grampletpane.py
Labels: bug

#971 Fix GEDCOM import when family is missing; import created a missing note
  gramps/plugins/lib/libgedcom.py
Labels: bug

#957 Fix ExportPkg so errors are not lost, and has progress bar for media
  gramps/gui/plug/export/_exportassistant.py
  gramps/plugins/export/exportpkg.py
Labels: bug

#959 Fix Progen import to correctly handle AKA surnames
  gramps/plugins/importer/importprogen.py
  gramps/plugins/lib/libprogen.py
Labels: bug

#945 Fix dbapi db to warn/prevent opening newer schema versions
  gramps/gen/db/generic.py
Labels: bug

#962 Fix import file chooser filter to accept upper case extensions
  gramps/gui/dbloader.py
Labels: bug

#979 Make GuiDestinationOption Folder Icon start in users directory
  gramps/gui/plug/_guioptions.py
Labels: bug

#942 Improve CSV import to allow places that are not in enclosed order
  gramps/plugins/importer/importcsv.py
Labels: bug, enhancement

#965 Fix Lat/Long translated NSEW display and entry in rtl language;Store Lat/Long in place objects with NSEW always in English
  gramps/gen/utils/place.py
  gramps/gui/editors/editplace.py
  gramps/gui/editors/editplaceref.py
Labels: bug

#984 Update LDS Temple list
  data/lds.xml
  gramps/plugins/test/tools_test.py
Labels: bug

#972 Update _pythonmime.py
  gramps/gen/mime/_pythonmime.py
Labels: enhancement

#953 Narweb: Private notes for home, intro and contact
  gramps/plugins/webreport/contact.py
  gramps/plugins/webreport/home.py
  gramps/plugins/webreport/introduction.py
  gramps/plugins/webreport/narrativeweb.py
Labels: bug

#938 Pedigree View - Add Help context menu
  gramps/plugins/view/pedigreeview.py
Labels: Documentation, enhancement

#937 Add context menu entries for Gramplet Bar
  gramps/gui/widgets/grampletbar.py
Labels: Documentation, enhancement

#977 Narweb: enclosed places not correctly sorted.
  gramps/plugins/webreport/basepage.py
Labels: enhancement, work in progress

#983 Narrated Web: bad event links on media pages
  gramps/plugins/webreport/basepage.py
Labels: bug

#976 Geography: Add custom tiles provider
  gramps/gen/config.py
  gramps/plugins/lib/maps/constants.py
  gramps/plugins/lib/maps/geography.py
  gramps/plugins/lib/maps/osmgps.py
  gramps/plugins/view/geoclose.py
  gramps/plugins/view/geofamclose.py
  gramps/plugins/view/geomoves.py
  gramps/plugins/view/geoperson.py
  gramps/plugins/view/geoplaces.py
Labels: enhancement

#980 NAVWEB and WEBCAL: some minor corrections
  data/css/narrative-maps.css
  gramps/plugins/webreport/basepage.py
  gramps/plugins/webreport/common.py
  gramps/plugins/webreport/narrativeweb.py
  gramps/plugins/webreport/updates.py
  gramps/plugins/webreport/webcal.py
Labels: bug, enhancement

#992 Update ukrainian translation
  po/uk.po
Labels: Translation
