Repository gramps-project/gramps, pull requests merged in 2020-04, with the labels that each got.

#1004 Narweb: image size limit doesn't match tooltip
  gramps/plugins/webreport/narrativeweb.py
Labels: Documentation, bug

#1025 Geography: add a popup for a bad tiles path
  gramps/plugins/lib/maps/osmgps.py
Labels: bug

#1011 Same date of birth and death gives an error.
  gramps/plugins/tool/verify.py
Labels: bug

#1021 Narweb: Add family map to family pages
  data/css/Web_Basic-Ash.css
  data/css/Web_Basic-Blue.css
  data/css/Web_Basic-Cypress.css
  data/css/Web_Basic-Lilac.css
  data/css/Web_Basic-Peach.css
  data/css/Web_Basic-Spruce.css
  data/css/Web_Mainz.css
  data/css/Web_Nebraska.css
  gramps/plugins/webreport/basepage.py
  gramps/plugins/webreport/family.py
  gramps/plugins/webreport/narrativeweb.py
Labels: enhancement

#1024 Narweb: possibility to have more than 2 downloads
  gramps/plugins/webreport/download.py
  gramps/plugins/webreport/narrativeweb.py
Labels: enhancement

#1032 Protect SQLite3 locale from old-style Unicode locale characters.
  gramps/plugins/db/dbapi/sqlite.py
Labels: bug

#988 Try to fix exceptions on ManagedWindow close
  gramps/gui/managedwindow.py
Labels: bug

#995 Fix StyledText so serialize will match for style list order changes
  gramps/gen/lib/styledtext.py
  gramps/gen/lib/test/styledtext_test.py
Labels: bug

#998 Fix Date Display so that it uses LC_TIME if defined
  gramps/gen/datehandler/__init__.py
Labels: bug

#999 Update tag.py
  gramps/gui/views/tags.py
Labels: bug

#994 Add option that allows to use the name of the individual as title.
  gramps/plugins/textreport/indivcomplete.py
Labels: enhancement

#986 EditEvent callback
  gramps/gui/editors/editevent.py
Labels: enhancement

#1006 Speed up Event displaytab and gramplet
  gramps/gui/editors/displaytabs/eventrefmodel.py
  gramps/plugins/gramplet/events.py
Labels: enhancement

#1046 review french translation
  po/fr.po
Labels: Review Required, Translation, enhancement, work in progress
