Repository gramps-project/gramps, pull requests merged in 2020-08, with the labels that each got.

#1088 Fix and add objects to Polish translation of Gramps
  po/gramps.pot
  po/pl.po
Labels: Translation

#1092 Fix Charts/Pedigreeview tooltip Polish translation
  po/pl.po
Labels: Translation, bug

#1075 Events View: "Main Participants" column does not
  gramps/gui/views/treemodels/eventmodel.py
Labels: bug
