Repository gramps-project/gramps, pull requests merged in 2020-09, with the labels that each got.

#1106 Remove the resource-path file
  gramps/gen/utils/resourcepath.py
  setup.py
Labels: enhancement

#1105 Replace intltools-merge with msgfmt
  .gitignore
  MANIFEST.in
  data/gramps.applications
  data/gramps.desktop.in
  data/gramps.keys.in
  data/gramps.mime
  data/holidays.xml
  data/tips.xml
  data/tips.xml.in
  po/LINGUAS
  po/POTFILES.in
  po/genpot.sh
  po/its/holidays.its
  po/its/holidays.loc
  po/its/shared-mime-info.its
  po/its/shared-mime-info.loc
  po/its/tips.its
  po/its/tips.loc
  po/update_po.py
  setup.py
Labels: enhancement

#1110 Fix svgdrawdoc for text containing XML invalid characters
  gramps/plugins/docgen/svgdrawdoc.py
Labels: bug

#1103 Fix progress bar freeze due to changes in Gtk
  gramps/gui/dbloader.py
  gramps/gui/displaystate.py
  gramps/gui/uimanager.py
  gramps/gui/utils.py
  gramps/gui/viewmanager.py
Labels: bug

#1099 Fix crash sorting on columns in Selectors with TreeModels
  gramps/gui/selectors/baseselector.py
Labels: bug

#1111 Fix graphdoc to properly escape characters in ids for Graphviz
  gramps/gen/plug/docgen/graphdoc.py
Labels: bug

#1093 Check & Repair: search and fix bad "links" in StyledTextTags
  gramps/plugins/tool/check.py
Labels: bug, enhancement

#1112 Fix EditEventRef, EditPlaceRef, EditMediaRef, EditRepoRef for improperly saving objects in their object lists.
  gramps/gui/editors/editeventref.py
  gramps/gui/editors/editmediaref.py
  gramps/gui/editors/editplaceref.py
  gramps/gui/editors/editreporef.py
Labels: bug

#1113 Fix error in Birthday and Anniversary report
  gramps/plugins/textreport/birthdayreport.py
Labels: bug

#1114 Completing pip installability
  .travis.yml
  setup.py
Labels: enhancement

#1102 Install application icons into correct directories
  images/hicolor/16x16/apps/gramps.png
  images/hicolor/22x22/apps/gramps.png
  images/hicolor/24x24/apps/gramps.png
  images/hicolor/48x48/apps/gramps.png
  images/hicolor/scalable/apps/gramps.svg
  setup.py
Labels: enhancement

#1012 Move beta warning into the status bar
  gramps/gen/config.py
  gramps/gen/const.py
  gramps/gui/displaystate.py
  gramps/gui/grampsgui.py
  gramps/gui/widgets/statusbar.py
  gramps/version.py
Labels: enhancement

#1129 Fix travis build
  .travis.yml
Labels: bug

#1123 Update Spanish translations
  po/es.po
Labels: Translation

#1043 Revised and updated hu translation.
  po/hu.po
Labels: Translation

#1087 [New Dutch translation] Ready for 5.1.3 !!
  po/nl.po
Labels: Translation

#1121 Update Simplified Chinese translation
  po/zh_CN.po
Labels: Translation
