Repository gramps-project/gramps, pull requests merged in 2021-05, with the labels that each got.

#1182 Add Media filter rule 'HasMedia' to list of media rules for editor
  gramps/gen/filters/rules/media/__init__.py
Labels: bug

#1186 Fix CSV export of view to only put single CR character.
  gramps/gen/utils/docgen/csvtab.py
Labels: bug

#1187 Home Person setting does not convey in a Merge
  gramps/gen/merge/mergepersonquery.py
Labels: bug

#1188 geofamily crashes if a family has no father
  gramps/plugins/view/geofamily.py
Labels: bug

#1192 Fix References Gramplet for inadequate updates when other objects change
  gramps/plugins/gramplet/backlinks.py
Labels: bug

#1193 Fix libplaceview to avoid exception when mapservice is no longer present
  gramps/plugins/lib/libplaceview.py
Labels: bug

#1189 Fix db corrupted error message to make it apply to all db types
  gramps/cli/grampscli.py
  gramps/cli/user.py
  gramps/gui/dialog.py
Labels: bug

#1185 Display the event date in the backlinks gramplet
  gramps/plugins/gramplet/backlinks.py
Labels: enhancement

#1180 citations gramplet: add date, page, confidence
  gramps/gui/editors/displaytabs/citationembedlist.py
  gramps/gui/editors/displaytabs/citationrefmodel.py
  gramps/plugins/gramplet/citations.py
Labels: enhancement

#1138 In familysidebarfilter, search on each part of name
  gramps/gui/filters/sidebar/_familysidebarfilter.py
Labels: enhancement

#1203 Narrative web: Toggle bug for source attribute
  gramps/plugins/webreport/basepage.py
Labels: bug, enhancement

#1204 [translation] Hebrew update for v 5.2
  po/he.po
Labels: Translation

#1137 Update Simplified Chinese translation
  po/zh_CN.po
Labels: Translation

#1136 Update Dutch translation
  gramps/gen/datehandler/_date_nl.py
  gramps/plugins/rel/rel_nl.py
  po/nl.po
Labels: Translation

#1206 Translations update from Weblate
  po/sv.po
Labels: Translation

#1208 Update Simplified Chinese translation
  po/zh_CN.po
Labels: Translation

#1195 "Number of Parents" column in Person Views
  gramps/gui/views/treemodels/peoplemodel.py
Labels: enhancement

#1179 image magic exception if file not found, add bmp and tiff
  README.md
  gramps/gen/utils/image.py
Labels: bug, enhancement

#1220 Move comments away from translated strings
  gramps/cli/arghandler.py
  gramps/cli/clidbman.py
  po/gramps.pot
Labels: Translation

#1213 Various fixes to user-visible strings
  gramps/gui/glade/editcitation.glade
  gramps/gui/glade/editmedia.glade
  gramps/gui/glade/editname.glade
  gramps/gui/glade/editplace.glade
  gramps/gui/glade/editplaceref.glade
  gramps/plugins/drawreport/ancestortree.py
  gramps/plugins/drawreport/descendtree.py
  gramps/plugins/importer/importgedcom.glade
  gramps/plugins/webreport/narrativeweb.py
Labels: enhancement

#1222 Spelling: Python, media type, set up, could not
  gramps/grampsapp.py
Labels: enhancement

#1229 Update and improve Simplified Chinese translation
  po/zh_CN.po
Labels: Translation

#1221 Add the missing word
  gramps/plugins/test/reports_test.py
  gramps/plugins/test/tools_test.py
  gramps/plugins/tool/check.py
Labels: enhancement

#1232 Improve and correct the Simplified Chinese translation
  po/zh_CN.po
Labels: Translation

#1235 Update holidays.xml for Russian
  data/holidays.xml
Labels: Translation
