Repository gramps-project/gramps, pull requests merged in 2021-07, with the labels that each got.

#1275 Update Simplified Chinese translation
  po/zh_CN.po
Labels: Translation

#1272 Narweb: Inconsistency between the name of the link
  data/css/Web_Basic-Ash.css
  data/css/Web_Basic-Blue.css
  data/css/Web_Basic-Cypress.css
  data/css/Web_Basic-Lilac.css
  data/css/Web_Basic-Peach.css
  data/css/Web_Basic-Spruce.css
  data/css/Web_Mainz.css
  data/css/Web_Nebraska.css
  gramps/plugins/webreport/basepage.py
Labels: enhancement

#1228 Navweb: add place name to birth and death dates
  gramps/plugins/webreport/person.py
Labels: enhancement

#1282 Update and fix Simplified Chinese translation
  po/zh_CN.po
Labels: Translation

#1273 Fix bottombar always showing after restart, even when not wanted
  gramps/gui/views/pageview.py
Labels: bug

#1274 Fix for crash when changing views if part of toolbar is not shown
  gramps/gui/viewmanager.py
Labels: bug

#1278 Place editor, copy and paste of lat and long text
  gramps/gui/editors/editplace.py
  gramps/gui/editors/editplaceref.py
Labels: bug

#1285 probably-alive incorrect if death without date
  gramps/gen/utils/alive.py
Labels: bug
