Repository gramps-project/gramps, pull requests merged in 2021-06, with the labels that each got.

#1244 Use "Translator" tag when extracting comments for translators
  gramps/cli/arghandler.py
  gramps/cli/argparser.py
  gramps/cli/clidbman.py
  gramps/cli/plug/__init__.py
  gramps/gen/const.py
  gramps/gen/datehandler/_datedisplay.py
  gramps/gen/datehandler/_datestrings.py
  gramps/gen/display/name.py
  gramps/gen/lib/date.py
  gramps/gen/lib/name.py
  gramps/gen/plug/report/endnotes.py
  gramps/gen/plug/report/utils.py
  gramps/gui/aboutdialog.py
  gramps/gui/configure.py
  gramps/gui/editors/editfamily.py
  gramps/gui/editors/editplace.py
  gramps/gui/editors/editplaceref.py
  gramps/gui/merge/mergeperson.py
  gramps/gui/plug/_windows.py
  gramps/gui/plug/export/_exportoptions.py
  gramps/gui/plug/report/_reportdialog.py
  gramps/plugins/drawreport/calendarreport.py
  gramps/plugins/drawreport/descendtree.py
  gramps/plugins/gramplet/pedigreegramplet.py
  gramps/plugins/gramplet/persondetails.py
  gramps/plugins/gramplet/sessionloggramplet.py
  gramps/plugins/gramplet/whatsnext.py
  gramps/plugins/graph/gvfamilylines.py
  gramps/plugins/importer/importcsv.py
  gramps/plugins/importer/importgeneweb.py
  gramps/plugins/importer/importvcard.py
  gramps/plugins/importer/importxml.py
  gramps/plugins/lib/librecords.py
  gramps/plugins/lib/libtreebase.py
  gramps/plugins/quickview/filterbyname.py
  gramps/plugins/quickview/samesurnames.py
  gramps/plugins/textreport/birthdayreport.py
  gramps/plugins/textreport/detancestralreport.py
  gramps/plugins/textreport/detdescendantreport.py
  gramps/plugins/textreport/familygroup.py
  gramps/plugins/textreport/indivcomplete.py
  gramps/plugins/textreport/numberofancestorsreport.py
  gramps/plugins/textreport/placereport.py
  gramps/plugins/tool/changetypes.py
  gramps/plugins/tool/check.py
  gramps/plugins/tool/eventnames.py
  gramps/plugins/tool/mergecitations.py
  gramps/plugins/tool/notrelated.py
  gramps/plugins/tool/verify.py
  gramps/plugins/view/relview.py
  gramps/plugins/webreport/basepage.py
  gramps/plugins/webreport/calendar.py
  gramps/plugins/webreport/webcal.py
  gramps/plugins/webstuff/webstuff.py
  po/gramps.pot
  po/update_po.py
Labels: Translation, enhancement

#1243 Translations update from Weblate
  po/ar.po
  po/bg.po
  po/br.po
  po/ca.po
  po/cs.po
  po/da.po
  po/de.po
  po/el.po
  po/en_GB.po
  po/eo.po
  po/es.po
  po/fi.po
  po/fr.po
  po/ga.po
  po/he.po
  po/hr.po
  po/hu.po
  po/is.po
  po/it.po
  po/ja.po
  po/lt.po
  po/mk.po
  po/nb.po
  po/nl.po
  po/nn.po
  po/pl.po
  po/pt_BR.po
  po/pt_PT.po
  po/ro.po
  po/ru.po
  po/sk.po
  po/sl.po
  po/sq.po
  po/sr.po
  po/sr_Latn.po
  po/sv.po
  po/ta.po
  po/tr.po
  po/uk.po
  po/vi.po
  po/zh_CN.po
  po/zh_HK.po
  po/zh_TW.po
Labels: enhancement

#1225 narrativeweb.py language reworked
  gramps/plugins/webreport/narrativeweb.py
Labels: enhancement

#1242 Fix spelling and remove extra newline
  gramps/plugins/importer/importxml.py
Labels: enhancement

#1197 Limit print statement by using logging module
  gramps/gui/uimanager.py
Labels: enhancement

#1239 README.md: update
  README.md
Labels: Documentation

#1237 INSTALL: Bump required Python version to 3.5
  INSTALL
Labels: Documentation

#1238 FAQ: update
  FAQ
Labels: Documentation

#1245 Translations update from Weblate
  po/de_AT.po
Labels: Translation

#1145 New Austrian German translation
  gramps/gen/utils/grampslocale.py
  po/LINGUAS
  po/de_AT.po
  setup.py
Labels: Translation

#1260 Navweb: Solve a merge problem about msgctxt
  gramps/plugins/webreport/basepage.py
Labels: bug

#1248 Improve and correct Simplified Chinese translation
  po/zh_CN.po
Labels: Translation

#1267 Correct and improve Simplified Chinese translation
  po/zh_CN.po
Labels: Translation
