Repository gramps-project/gramps, pull requests merged in 2022-02, with the labels that each got.

#1313 Narweb: translation problem + missing events on markers
  gramps/plugins/webreport/addressbooklist.py
  gramps/plugins/webreport/person.py
Labels: bug, enhancement

#1332 Fix negative Span when dates are not Gregorian
  gramps/gen/lib/date.py
  gramps/gen/lib/test/date_test.py
Labels: bug

#1307 '<' not supported between 2 instances of IndexMark
  gramps/plugins/drawreport/calendarreport.py
Labels: bug

#1296 Solve InterpolationSyntaxError if "%" in a string
  gramps/gui/widgets/grampletpane.py
Labels: bug

#1323 Update polish tanslation
  po/pl.po
Labels: Translation

#1333 Fix place object element order in DTD and RNG schemas
  data/grampsxml.dtd
  data/grampsxml.rng
Labels: bug

#1298 Strange behavior for the scrollbar in the bottombar
  gramps/gui/views/pageview.py
  gramps/gui/widgets/grampletbar.py
Labels: bug

#935 Family group report enhancements
  gramps/plugins/textreport/familygroup.py
Labels: enhancement, Documentation

#941 Improved Age Stats gramplet
  gramps/gui/widgets/__init__.py
  gramps/gui/widgets/histogram.py
  gramps/plugins/gramplet/agestats.py
  po/POTFILES.skip
Labels: enhancement, Documentation, Conflicts

#1019 Add Phone/Postal to Addresses tab of Person editor
  gramps/gui/editors/displaytabs/addrembedlist.py
  gramps/gui/editors/displaytabs/addressmodel.py
Labels: enhancement, Documentation

#1033 Improve rst manpage syntax
  data/man/en.rst
  data/man/gramps.1.in
Labels: bug, enhancement

#1054 Add godparent as event role
  gramps/gen/lib/eventroletype.py
  gramps/plugins/test/tools_test.py
Labels: enhancement, Documentation

#964 Update INCOMPLETE_TRANSLATIONS
  gramps/gen/utils/grampslocale.py
Labels: Translation

#1153 Move MIME icons together with other hicolor icons
  images/hicolor/48x48/mimetypes/application-x-gedcom.png
  images/hicolor/48x48/mimetypes/application-x-geneweb.png
  images/hicolor/48x48/mimetypes/application-x-gramps-package.png
  images/hicolor/48x48/mimetypes/application-x-gramps-xml.png
  images/hicolor/48x48/mimetypes/application-x-gramps.png
  images/hicolor/scalable/mimetypes/application-x-gedcom.svg
  images/hicolor/scalable/mimetypes/application-x-geneweb.svg
  images/hicolor/scalable/mimetypes/application-x-gramps-package.svg
  images/hicolor/scalable/mimetypes/application-x-gramps-xml.svg
  images/hicolor/scalable/mimetypes/application-x-gramps.svg
  setup.py
Labels: enhancement

#1077 Remove xdg-utils dependency
  README.md
  debian/control
  gramps/gui/utils.py
Labels: Documentation

#974 Simplify error construction in argument parser
  gramps/cli/argparser.py
  gramps/cli/test/argparser_test.py
Labels: enhancement, Code Quality

#975 Simplify looping across Gramps.
  gramps/cli/argparser.py
  gramps/cli/test/argparser_test.py
  gramps/gen/db/base.py
  gramps/gen/filters/_paramfilter.py
  gramps/gen/filters/rules/_rule.py
  gramps/gen/lib/test/date_test.py
  gramps/gen/plug/docgen/fontscale.py
  gramps/gen/plug/report/_book.py
  gramps/gen/plug/report/_options.py
  gramps/gen/plug/report/utils.py
  gramps/gen/recentfiles.py
  gramps/gen/simple/_simpletable.py
  gramps/gui/editors/displaytabs/gallerytab.py
  gramps/gui/editors/displaytabs/surnametab.py
  gramps/gui/editors/editdate.py
  gramps/gui/editors/editperson.py
  gramps/gui/plug/export/_exportassistant.py
  gramps/gui/plug/tool.py
  gramps/gui/selectors/baseselector.py
  gramps/gui/uimanager.py
  gramps/gui/views/listview.py
  gramps/gui/views/treemodels/flatbasemodel.py
  gramps/gui/views/treemodels/treebasemodel.py
  gramps/gui/widgets/fanchart.py
  gramps/gui/widgets/fanchart2way.py
  gramps/gui/widgets/fanchartdesc.py
  gramps/gui/widgets/grampletpane.py
  gramps/gui/widgets/shortlistcomboentry.py
  gramps/plugins/docgen/cairodoc.py
  gramps/plugins/docgen/latexdoc.py
  gramps/plugins/drawreport/descendtree.py
  gramps/plugins/drawreport/statisticschart.py
  gramps/plugins/gramplet/leak.py
  gramps/plugins/graph/gvfamilylines.py
  gramps/plugins/lib/libcairodoc.py
  gramps/plugins/lib/libprogen.py
  gramps/plugins/rel/rel_da.py
  gramps/plugins/rel/rel_is.py
  gramps/plugins/rel/rel_no.py
  gramps/plugins/rel/rel_sv.py
  gramps/plugins/sidebar/categorysidebar.py
  gramps/plugins/sidebar/dropdownsidebar.py
  gramps/plugins/sidebar/expandersidebar.py
  gramps/plugins/textreport/detdescendantreport.py
Labels: Code Quality

#1014 [AncestorGramplet]: CopyAll functionality
  gramps/plugins/gramplet/ancestor.py
Labels: enhancement, Documentation

#1018 Remove no_magic support; which was not working for dbapi
  gramps/gen/utils/db.py
  gramps/gen/utils/unknown.py
  gramps/plugins/db/dbapi/dbapi.py
  gramps/plugins/importer/importxml.py
  gramps/plugins/lib/libgedcom.py
  gramps/plugins/tool/check.py
Labels: bug

#1120 Add __main__.py
  gramps/__main__.py
  gramps/cli/argparser.py
  gramps/cli/test/cli_test.py
  po/POTFILES.skip
Labels: enhancement, Documentation

#1155 Add gramps_id to repository & note text data lists
  gramps/gen/lib/note.py
  gramps/gen/lib/repo.py
Labels: bug

#1309 Fix Place.get_text_data_child_list
  gramps/gen/lib/place.py
Labels: bug

#1161 Allow user to set default calendar in date editor
  gramps/gen/config.py
  gramps/gui/configure.py
  gramps/gui/editors/editdate.py
Labels: enhancement

#1300 Add new Indonesian translation
  gramps/gen/utils/grampslocale.py
Labels: Translation

#951 Provide an option to "hide" the LDS tab
  gramps/gen/config.py
  gramps/gui/configure.py
  gramps/gui/editors/editfamily.py
  gramps/gui/editors/editperson.py
Labels: enhancement, Documentation

#1040 Relationship Graph; Add option for 'offset parents', replacing/expanding 'use subgraph'
  gramps/gen/plug/docgen/graphdoc.py
  gramps/plugins/graph/gvfamilylines.py
  gramps/plugins/graph/gvrelgraph.py
Labels: bug, enhancement

#1050 enable "file:///" URI paths for addons location
  gramps/gen/plug/utils.py
Labels: bug

#1056 Teach DateParser about calendar quarter dates
  gramps/gen/datehandler/_dateparser.py
  gramps/gen/datehandler/test/dateparser_test.py
Labels: enhancement, Documentation

#1060 Geography: better handling of bad tile path
  gramps/plugins/lib/maps/geography.py
  gramps/plugins/view/geoclose.py
  gramps/plugins/view/geoevents.py
  gramps/plugins/view/geofamclose.py
  gramps/plugins/view/geofamily.py
  gramps/plugins/view/geomoves.py
  gramps/plugins/view/geoperson.py
  gramps/plugins/view/geoplaces.py
Labels: bug

#1064 Add Abbreviation Column to Source and Citation selectors
  gramps/gui/selectors/selectcitation.py
  gramps/gui/selectors/selectsource.py
Labels: enhancement, Documentation

#1073 [PedigreeView] fix font color in boxes (bug 11799)
  gramps/gui/test/utils_test.py
  gramps/gui/utils.py
  gramps/plugins/view/pedigreeview.py
Labels: bug, Documentation

#1082 Add Catalan holidays
  data/holidays.xml
Labels: enhancement

#1107 Add Italian holidays
  data/holidays.xml
Labels: enhancement, Documentation, Conflicts

#1069 Symbols enhancement.
  gramps/gen/config.py
  gramps/gen/utils/libformatting.py
  gramps/gen/utils/symbols.py
  gramps/gui/configure.py
  gramps/gui/widgets/fanchart.py
  gramps/plugins/view/pedigreeview.py
  gramps/plugins/view/relview.py
Labels: bug, Documentation, Code Quality

#1166 Add option name_format to treedoc
  gramps/gen/plug/docgen/treedoc.py
Labels: enhancement

#1063 Update welcome gramplet
  gramps/plugins/gramplet/welcomegramplet.py
Labels: enhancement, Documentation, Needs Testing

#1098 Get Note LINK references updated for object deletes or merges
  gramps/gen/db/base.py
  gramps/gen/filters/rules/test/media_rules_test.py
  gramps/gen/lib/note.py
  gramps/gen/lib/notebase.py
  gramps/gen/lib/primaryobj.py
  gramps/gen/lib/test/merge_test.py
  gramps/gen/merge/mergecitationquery.py
  gramps/gen/merge/mergeeventquery.py
  gramps/gen/merge/mergefamilyquery.py
  gramps/gen/merge/mergemediaquery.py
  gramps/gen/merge/mergenotequery.py
  gramps/gen/merge/mergepersonquery.py
  gramps/gen/merge/mergeplacequery.py
  gramps/gen/merge/mergerepositoryquery.py
  gramps/gen/merge/mergesourcequery.py
  gramps/gen/merge/test/merge_ref_test.py
  gramps/gui/dialog.py
  gramps/gui/editors/__init__.py
  gramps/gui/editors/displaytabs/backrefmodel.py
  gramps/gui/editors/editcitation.py
  gramps/gui/editors/editevent.py
  gramps/gui/editors/editmedia.py
  gramps/gui/editors/editnote.py
  gramps/gui/editors/editplace.py
  gramps/gui/editors/editrepository.py
  gramps/gui/editors/editsource.py
  gramps/gui/utils.py
  gramps/gui/views/listview.py
  gramps/plugins/lib/libpersonview.py
  gramps/plugins/lib/libplaceview.py
  gramps/plugins/lib/libsourceview.py
  gramps/plugins/view/citationlistview.py
  gramps/plugins/view/citationtreeview.py
  gramps/plugins/view/eventview.py
  gramps/plugins/view/familyview.py
  gramps/plugins/view/mediaview.py
  gramps/plugins/view/noteview.py
  gramps/plugins/view/repoview.py
  gramps/plugins/view/sourceview.py
Labels: bug, enhancement
