Repository gramps-project/gramps, pull requests merged in 2022-03, with the labels that each got.

#1017 Geography: better management when closing the database
  gramps/gen/config.py
  gramps/plugins/lib/maps/cairoprint.py
  gramps/plugins/lib/maps/constants.py
  gramps/plugins/lib/maps/datelayer.py
  gramps/plugins/lib/maps/dummylayer.py
  gramps/plugins/lib/maps/dummynogps.py
  gramps/plugins/lib/maps/geography.py
  gramps/plugins/lib/maps/kmllayer.py
  gramps/plugins/lib/maps/libkml.py
  gramps/plugins/lib/maps/lifewaylayer.py
  gramps/plugins/lib/maps/markerlayer.py
  gramps/plugins/lib/maps/messagelayer.py
  gramps/plugins/lib/maps/osmgps.py
  gramps/plugins/lib/maps/placeselection.py
  gramps/plugins/lib/maps/selectionlayer.py
  gramps/plugins/view/geoclose.py
  gramps/plugins/view/geoevents.py
  gramps/plugins/view/geofamclose.py
  gramps/plugins/view/geofamily.py
  gramps/plugins/view/geomoves.py
  gramps/plugins/view/geoperson.py
  gramps/plugins/view/geoplaces.py
Labels: enhancement, Documentation, Conflicts

#1324 Fix bug 12535: "Descendants" is misspelled
  gramps/plugins/view/geomoves.py
Labels: bug

#1330 Add Turkish holidays
  data/holidays.xml
Labels: enhancement

#1334 Add Turkish Relationship Calculator
  gramps/plugins/rel/rel_tr.py
  gramps/plugins/rel/relplugins.gpr.py
  po/POTFILES.skip
Labels: Translation

#1340 Add xdg-utils to no longer needed list in README
  README.md
Labels: enhancement

#1349 Link to translated wiki pages in welcome gramplet
  gramps/plugins/gramplet/welcomegramplet.py
Labels: bug

#1356 Add more date handler tests
  gramps/gen/datehandler/_date_cs.py
  gramps/gen/datehandler/_date_da.py
  gramps/gen/datehandler/_date_hu.py
  gramps/gen/datehandler/_date_is.py
  gramps/gen/datehandler/_date_ja.py
  gramps/gen/datehandler/_date_pt.py
  gramps/gen/datehandler/_date_sr.py
  gramps/gen/datehandler/_date_zh_CN.py
  gramps/gen/datehandler/_date_zh_TW.py
  gramps/gen/datehandler/_dateparser.py
  gramps/gen/datehandler/test/datehandler_test.py
Labels: enhancement

#1151 Move temp directory out of HOME_DIR
  gramps/cli/argparser.py
  gramps/cli/test/cli_test.py
  gramps/gen/const.py
  gramps/gen/merge/test/merge_ref_test.py
  gramps/gen/utils/file.py
  gramps/gen/utils/test/file_test.py
  gramps/plugins/test/exports_test.py
  gramps/plugins/test/imports_test.py
Labels: enhancement

#1147 Skip time-consuming calls when debug logging is disabled
  gramps/gen/db/dummydb.py
  gramps/gen/db/txn.py
  gramps/gen/db/utils.py
  gramps/gen/dbstate.py
Labels: bug, enhancement

#1160 Gramps crashes on import of large KML file
  gramps/plugins/lib/maps/geography.py
Labels: enhancement

#1170 Date input: allow yyyy-mm for iso format
  gramps/gen/datehandler/_datedisplay.py
  gramps/gen/datehandler/_dateparser.py
Labels: enhancement

#1174 Add "All supported files" as file type selection
  gramps/gui/dbloader.py
Labels: enhancement

#1181 Geography cleanup
  gramps/plugins/lib/maps/geography.py
  gramps/plugins/view/geoclose.py
  gramps/plugins/view/geoevents.py
  gramps/plugins/view/geofamclose.py
  gramps/plugins/view/geoperson.py
  gramps/plugins/view/geoplaces.py
Labels: enhancement

#1259 Enhance information dialog to display simple tables
  gramps/gui/dialog.py
  gramps/plugins/importer/importxml.py
Labels: enhancement

#1233 Add round trip Ancestry.com _APID tag support
  gramps/plugins/export/exportgedcom.py
  gramps/plugins/lib/libgedcom.py
Labels: enhancement

#1236 Kinship report: change max number of generations.
  gramps/plugins/textreport/kinshipreport.py
Labels: enhancement

#1240 Childreftype.py: adding context
  gramps/gen/lib/childreftype.py
Labels: enhancement, Translation

#1365 Remove old translation context separators
  gramps/gen/datehandler/_datestrings.py
  gramps/gen/utils/grampslocale.py
  po/ar.po
  po/bg.po
  po/br.po
  po/ca.po
  po/cs.po
  po/da.po
  po/de.po
  po/de_AT.po
  po/el.po
  po/en_GB.po
  po/eo.po
  po/es.po
  po/fi.po
  po/fr.po
  po/ga.po
  po/gramps.pot
  po/he.po
  po/hr.po
  po/hu.po
  po/id.po
  po/is.po
  po/it.po
  po/ja.po
  po/lt.po
  po/mk.po
  po/nb.po
  po/nl.po
  po/nn.po
  po/pl.po
  po/pt_BR.po
  po/pt_PT.po
  po/ro.po
  po/ru.po
  po/sk.po
  po/sl.po
  po/sq.po
  po/sr.po
  po/sr_Latn.po
  po/sv.po
  po/ta.po
  po/tr.po
  po/uk.po
  po/vi.po
  po/zh_CN.po
  po/zh_HK.po
  po/zh_TW.po
Labels: enhancement

#1257 Update _exportassistant.py
  gramps/gui/plug/export/_exportassistant.py
Labels: enhancement

#1303 removespaces.py: Add context
  gramps/gen/filters/rules/place/_hasdata.py
  gramps/plugins/tool/removespaces.py
Labels: Translation

#1269 Display "[Missing surname]" for blank surname in peopletreemodel
  gramps/gui/views/treemodels/peoplemodel.py
Labels: enhancement

#1367 Fix package installation failures in CI
  .github/workflows/gramps-ci.yml
Labels: bug

#1305 Update citationembedlist.py
  gramps/gui/editors/displaytabs/citationembedlist.py
Labels: enhancement

#1280 Narweb: some fixes to alphabet_navigation
  gramps/plugins/webreport/alphabeticindex.py
  gramps/plugins/webreport/common.py
  gramps/plugins/webreport/event.py
  gramps/plugins/webreport/family.py
  gramps/plugins/webreport/narrativeweb.py
  gramps/plugins/webreport/person.py
  gramps/plugins/webreport/place.py
  gramps/plugins/webreport/surnamelist.py
Labels: bug

#1316 Add Back/Forward labels to CitationTree view
  gramps/plugins/view/citationtreeview.py
Labels: bug

#1319 Calendar gramplet: add the name of the days.
  gramps/plugins/gramplet/calendargramplet.py
Labels: enhancement

#1341 Crash in narrative web if invalid latitude/longitude
  gramps/plugins/webreport/basepage.py
  gramps/plugins/webreport/place.py
Labels: bug

#1347 Skip test3b_delete_tree_constraint iff $HOME is a subdirectory of /tmp
  gramps/test/test/test_util_test.py
Labels: bug

#1351 Some Persian calendar dates are invalid
  gramps/gen/lib/gcalendar.py
Labels: bug

#1352 Fix unit tests requiring English locale
  gramps/gen/filters/rules/test/event_rules_test.py
  gramps/gen/filters/rules/test/family_rules_test.py
  gramps/gen/filters/rules/test/person_rules_test.py
  gramps/gen/utils/unittest.py
  po/POTFILES.skip
Labels: bug

#1359 Cannot show spouse's name in Records Report
  gramps/plugins/lib/librecords.py
Labels: bug

#1369 Enable markup in ODF backend
  gramps/plugins/docgen/odfdoc.py
Labels: enhancement

#1295 Show note type in the Notes plugin
  gramps/plugins/gramplet/notes.py
Labels: enhancement

#1314 CSV: possibility to select the dialect.
  gramps/gen/config.py
  gramps/gen/utils/docgen/csvtab.py
  gramps/gui/csvdialect.py
  gramps/gui/views/listview.py
  gramps/plugins/export/export.gpr.py
  gramps/plugins/export/exportcsv.py
  gramps/plugins/importer/importcsv.py
  po/POTFILES.in
Labels: enhancement

#1370 Allow gramplets to have an orientation dependent layout
  gramps/gen/plug/_gramplet.py
  gramps/gui/views/pageview.py
  gramps/gui/widgets/grampletbar.py
  gramps/plugins/gramplet/gallery.py
Labels: enhancement, Needs Testing

#1363 Add support for thumbnailer plugins
  gramps/gen/const.py
  gramps/gen/plug/__init__.py
  gramps/gen/plug/_manager.py
  gramps/gen/plug/_pluginreg.py
  gramps/gen/plug/_thumbnailer.py
  gramps/gen/utils/thumbnails.py
  gramps/gui/editors/addmedia.py
  gramps/plugins/thumbnailer/__init__.py
  gramps/plugins/thumbnailer/gnomethumb.py
  gramps/plugins/thumbnailer/imagethumb.py
  gramps/plugins/thumbnailer/thumb.gpr.py
  po/POTFILES.in
  po/POTFILES.skip
Labels: enhancement
