Repository gramps-project/gramps, pull requests merged in 2022-01, with the labels that each got.

#1268 datehandler and relationship calculator with de_AT
  gramps/gen/datehandler/_date_de.py
  gramps/plugins/rel/rel_de_AT.py
  gramps/plugins/rel/relplugins.gpr.py
Labels: bug

#1321 Minor update to zh_CN translation
  po/zh_CN.po
Labels: Translation

#1241 Use GitHub Actions to run continuous integration checks
  .github/workflows/gramps-ci.yml
  po/its/appdata.its
  po/its/appdata.loc
  setup.py
Labels: enhancement

#1294 Fix probably alive test
  gramps/gen/filters/rules/test/person_rules_test.py
Labels: bug

#1283 OsmGpsMap-CRITICAL: Map source setup called twice
  gramps/plugins/lib/maps/geography.py
  gramps/plugins/lib/maps/osmgps.py
  gramps/plugins/view/geoclose.py
  gramps/plugins/view/geofamclose.py
Labels: bug

#1287 Fix error when trying to close name editor during long name group mapping view rebuild.
  gramps/gui/editors/editname.py
Labels: bug

#1288 Fix exception when removing a group name in Sqlite db when group name is already missing.
  gramps/plugins/db/dbapi/dbapi.py
Labels: bug

#1289 Fix Statusbar progress being shown before use
  gramps/gui/viewmanager.py
Labels: bug

#1290 Place editor, lat and long text are swapped
  gramps/gui/editors/editplace.py
  gramps/gui/editors/editplaceref.py
Labels: bug

#1291 Group As Override is ignored when the Surname is
  gramps/gen/display/name.py
Labels: bug
