Repository gramps-project/gramps, pull requests merged in 2023-05, with the labels that each got.

#1430 Give consistency to short months in Spanish
  gramps/gen/datehandler/_date_es.py
Labels: Translation

#1424 Fix crash when invalid note link
  gramps/gen/proxy/referencedbyselection.py
  gramps/gui/widgets/styledtexteditor.py
  gramps/plugins/lib/libhtmlbackend.py
Labels: bug

#1418 Fix incorrect title of event schema attribute_list
  gramps/gen/lib/event.py
Labels: bug

#1407 Make "gramps -v" consistent with Prerequisites Checker Gramplet
  gramps/grampsapp.py
Labels: bug, enhancement

#1413 Narrative web: Solves some problems
  gramps/plugins/webreport/basepage.py
  gramps/plugins/webreport/common.py
  gramps/plugins/webreport/family.py
  gramps/plugins/webreport/narrativeweb.py
  gramps/plugins/webreport/person.py
  gramps/plugins/webreport/place.py
Labels: bug, enhancement

#1393 Fix IndexError that sometimes occurs when changing view
  gramps/gui/viewmanager.py
Labels: bug

#1401 Fix corrupted NOTE tag in Gedcom export
  gramps/plugins/export/exportgedcom.py
Labels: bug

#1412 HtmlDoc.add_media: unique filename for cropped images
  gramps/plugins/docgen/htmldoc.py
Labels: bug

#1408 Try to import berkeleydb if bsddb3 isn't found.
  gramps/grampsapp.py
  gramps/gui/aboutdialog.py
  gramps/gui/logger/_errorreportassistant.py
  gramps/plugins/db/bsddb/bsddbtxn.py
  gramps/plugins/db/bsddb/cursor.py
  gramps/plugins/db/bsddb/read.py
  gramps/plugins/db/bsddb/summary.py
  gramps/plugins/db/bsddb/test/cursor_test.py
  gramps/plugins/db/bsddb/undoredo.py
  gramps/plugins/db/bsddb/upgrade.py
  gramps/plugins/db/bsddb/write.py
  gramps/plugins/gramplet/leak.py
  mac/patches/gramps-berkeleydb.patch
Labels: bug

#1405 Use date-specific place in report substitution variables
  gramps/plugins/lib/libsubstkeyword.py
Labels: bug

#1398 Geography View: Fix number of arguments in add_bookmark method
  gramps/plugins/lib/maps/geography.py
Labels: bug

#1395 Revert "Enclose tree report image path and file name in braces"
  gramps/gen/plug/docgen/treedoc.py
Labels: bug, Approved

#1380 Fix a wrong operator bug in the web calendar report
  gramps/plugins/webreport/webcal.py
Labels: bug

#1377 Check that view exists before calling post_create method
  gramps/gui/viewmanager.py
Labels: bug

#1374 Fix Event compare tool to display enclosed places properly
  gramps/plugins/tool/eventcmp.py
Labels: bug
