Repository gramps-project/gramps, pull requests merged in 2023-09, with the labels that each got.

#1562 Update width of Gramps ID fields in editors
  gramps/gui/glade/editevent.glade
  gramps/gui/glade/editperson.glade
  gramps/gui/glade/editplace.glade
  gramps/gui/glade/editplaceref.glade
  gramps/gui/glade/editsource.glade
Labels: bug

#1568 Small changes to Addon Manager project editor
  gramps/gui/plug/_windows.py
Labels: bug

#1569 Make the Addon Manager available without a tree loaded
  gramps/gui/grampsgui.py
Labels: bug

#1571 Fix addon prerequisites install
  gramps/gen/const.py
  gramps/gui/plug/_windows.py
Labels: bug

#1550 verify tool: convert the ListStore to a TreeStore
  gramps/plugins/tool/verify.py
Labels: enhancement

#1517 Add Hebrew date handler
  gramps/gen/datehandler/__init__.py
  gramps/gen/datehandler/_date_he.py
  gramps/gen/datehandler/_datehandler.py
  po/POTFILES.skip
Labels: Translation

#1575 Add Hebrew relationship calculator
  gramps/plugins/rel/rel_he.py
  gramps/plugins/rel/relplugins.gpr.py
  po/POTFILES.skip
Labels: Translation

#1576 Capitalize "python" in the Addon Manager settings
  gramps/gui/plug/_windows.py
Labels: Code Quality

#1577 Fix Addon Manager help link
  gramps/gui/plug/_windows.py
Labels: bug

#1578 Fix report dialog error when no active person selected
  gramps/gui/plug/_dialogs.py
Labels: bug

#1574 Verification Tool - 8 more rules + performance enhancements
  gramps/plugins/tool/verify.py
Labels: enhancement

#1580 Fix translated tip of the day entries with quote characters
  gramps/gui/tipofday.py
Labels: bug

#1581 Rename "Ancestor View" to "Pedigree View" in Tip of the Day
  data/tips.xml
Labels: bug

#1584 Update a couple of strings to clarify the Addon Manager UI
  gramps/gui/plug/_windows.py
Labels: bug

#1583 Allow multiple versions in gi requirements
  gramps/gen/utils/requirements.py
Labels: bug

#1586 Update welcomegramplet.py - add margin
  gramps/plugins/gramplet/welcomegramplet.py
Labels: bug

#1588 Invalidate caches after new python modules are installed
  gramps/gui/plug/_windows.py
Labels: bug

#1590 Refine Hebrew About modifiers in date parser
  gramps/gen/datehandler/_date_he.py
Labels: Translation

#1594 Fix crash when displaying settings in context menu popup
  gramps/plugins/view/pedigreeview.py
Labels: bug

#1593 Minor update to Simplified Chinese translation
  po/zh_CN.po
Labels: Translation
