Repository gramps-project/gramps, pull requests merged in 2023-08, with the labels that each got.

#1488 Fix incorrect relationship symbols
  gramps/gen/utils/symbols.py
Labels: bug

#1493 Fix bottombar not saving size
  gramps/gui/views/pageview.py
Labels: bug

#1489 Fix changes reverted by mistake
  gramps/gui/configure.py
Labels: bug

#1487 Set default column size in list views
  gramps/gui/views/listview.py
Labels: bug

#1500 Fix typo in commit 354e191ea0b7f8ebc93c5bd5a0618fedf6385186
  gramps/gen/utils/grampslocale.py
Labels: bug

#1497 Save column sizes before a rebuild
  gramps/gui/views/listview.py
  gramps/gui/widgets/persistenttreeview.py
Labels: bug

#1501 Update po snippet generation to output msgctxt
  gramps/gen/datehandler/_datestrings.py
Labels: bug

#1504 Check for Windows executables in addon requirements
  gramps/gen/utils/requirements.py
Labels: bug

#1505 Improve Addon Manager search
  gramps/gui/plug/_windows.py
Labels: bug

#1508 Fix genealogical symbols
  gramps/gen/utils/symbols.py
Labels: bug

#1509 Better URLs for gramplet bar help
  gramps/gui/widgets/grampletbar.py
Labels: bug

#1514 Improved organization of the Addon Manager filter lists
  gramps/gen/plug/_pluginreg.py
  gramps/gui/plug/_windows.py
Labels: bug

#1522 Fix system locale detection on MS Windows.
  gramps/gen/utils/win32locale.py
Labels: bug

#1516 Fix glocale problems on Windows
  gramps/gen/utils/grampslocale.py
Labels: bug

#1519 Fixes #11744, #12626, #12629, #12963 delete surname
  gramps/gui/editors/displaytabs/surnametab.py
Labels: bug

#1523 Addon manager changes
  gramps/gen/plug/utils.py
  gramps/gui/plug/_windows.py
Labels: bug

#1525 Add a scrolled window to the preferences data tab
  gramps/gui/configure.py
Labels: bug

#1524 Add Farsi to Microsoft Windows Locale list.
  gramps/gen/utils/win32locale.py
Labels: Translation

#1496 Add support for Hebrew prefixes
  gramps/plugins/lib/libnarrate.py
Labels: Translation

#1498 Fix 12945: Track all tab settings separately
  gramps/gui/editors/displaytabs/addrembedlist.py
  gramps/gui/editors/displaytabs/attrembedlist.py
  gramps/gui/editors/displaytabs/backreflist.py
  gramps/gui/editors/displaytabs/citationbackreflist.py
  gramps/gui/editors/displaytabs/citationembedlist.py
  gramps/gui/editors/displaytabs/embeddedlist.py
  gramps/gui/editors/displaytabs/eventattrembedlist.py
  gramps/gui/editors/displaytabs/eventbackreflist.py
  gramps/gui/editors/displaytabs/eventembedlist.py
  gramps/gui/editors/displaytabs/familyattrembedlist.py
  gramps/gui/editors/displaytabs/familyldsembedlist.py
  gramps/gui/editors/displaytabs/groupembeddedlist.py
  gramps/gui/editors/displaytabs/ldsembedlist.py
  gramps/gui/editors/displaytabs/locationembedlist.py
  gramps/gui/editors/displaytabs/mediaattrembedlist.py
  gramps/gui/editors/displaytabs/mediabackreflist.py
  gramps/gui/editors/displaytabs/nameembedlist.py
  gramps/gui/editors/displaytabs/notebackreflist.py
  gramps/gui/editors/displaytabs/notetab.py
  gramps/gui/editors/displaytabs/personbackreflist.py
  gramps/gui/editors/displaytabs/personeventembedlist.py
  gramps/gui/editors/displaytabs/personrefembedlist.py
  gramps/gui/editors/displaytabs/placebackreflist.py
  gramps/gui/editors/displaytabs/placenameembedlist.py
  gramps/gui/editors/displaytabs/placerefembedlist.py
  gramps/gui/editors/displaytabs/repoembedlist.py
  gramps/gui/editors/displaytabs/sourcebackreflist.py
  gramps/gui/editors/displaytabs/srcattrembedlist.py
  gramps/gui/editors/displaytabs/surnametab.py
  gramps/gui/editors/displaytabs/webembedlist.py
  gramps/gui/editors/editaddress.py
  gramps/gui/editors/editattribute.py
  gramps/gui/editors/editchildref.py
  gramps/gui/editors/editcitation.py
  gramps/gui/editors/editevent.py
  gramps/gui/editors/editeventref.py
  gramps/gui/editors/editfamily.py
  gramps/gui/editors/editldsord.py
  gramps/gui/editors/editmedia.py
  gramps/gui/editors/editmediaref.py
  gramps/gui/editors/editname.py
  gramps/gui/editors/editnote.py
  gramps/gui/editors/editperson.py
  gramps/gui/editors/editpersonref.py
  gramps/gui/editors/editplace.py
  gramps/gui/editors/editplaceref.py
  gramps/gui/editors/editreporef.py
  gramps/gui/editors/editrepository.py
  gramps/gui/editors/editsource.py
Labels: bug

#1530 Stamen Maps set aside
  gramps/plugins/lib/maps/constants.py
  gramps/plugins/lib/maps/geography.py
  gramps/plugins/lib/maps/osmgps.py
  gramps/plugins/mapservices/openstreetmap.py
  gramps/plugins/webreport/narrativeweb.py
Labels: bug

#1532 Fix vertical expansion of family tree manager list
  gramps/gui/dbman.py
  gramps/gui/glade/dbman.glade
Labels: bug

#1535 Fix trans_text keyword in xgettext
  po/gramps.pot
  po/update_po.py
Labels: bug

#1537 Fix crash when printing notes during endnote creation
  gramps/gen/plug/report/endnotes.py
  gramps/plugins/cite/default.py
Labels: bug

#1540 Fix Gedcom import tagging a note with an undefined tag handle
  data/tests/imp_PhonFax_dfs.gramps
  data/tests/imp_notetest_dfs.gramps
  gramps/plugins/lib/libgedcom.py
  gramps/plugins/test/imports_test.py
Labels: bug

#1542 No longer state that Gramps will close in the backup message
  gramps/gui/viewmanager.py
Labels: bug

#1541 Prevent fan chart title being overwritten by the chart
  gramps/plugins/drawreport/fanchart.py
Labels: bug

#1547 Fix translator date inflection comments
  gramps/gen/datehandler/_datedisplay.py
  po/gramps.pot
Labels: Translation

#1546 Fix black margin in project list with scrollbar
  gramps/gui/plug/_windows.py
Labels: bug

#1549 Include javascript files in installation
  setup.py
Labels: bug

#1555 Add missing cite and thumbnailer plugin directories to build script
  setup.py
Labels: bug

#1552 Fix sizing of the surname table in the name editor
  gramps/gui/editors/editname.py
  gramps/gui/glade/editname.glade
Labels: bug

#1553 Fix bug when deleting a row from a filtered flat list view
  gramps/gui/views/treemodels/flatbasemodel.py
Labels: bug

#1554 Add an extra requirements check after installing modules
  gramps/gui/plug/_windows.py
Labels: bug

#1556 Fix bug in endnotes citations
  gramps/gen/plug/report/endnotes.py
Labels: bug

#1551 Make the narrative web ltr and rtl.
  data/css/Web_Basic-Ash.css
  data/css/Web_Basic-Blue.css
  data/css/Web_Basic-Cypress.css
  data/css/Web_Basic-Lilac.css
  data/css/Web_Basic-Peach.css
  data/css/Web_Basic-Spruce.css
  data/css/Web_Mainz.css
  data/css/Web_Nebraska.css
  data/css/lightbox.css
  gramps/plugins/webreport/addressbooklist.py
  gramps/plugins/webreport/basepage.py
  gramps/plugins/webreport/calendar.py
  gramps/plugins/webreport/common.py
  gramps/plugins/webreport/event.py
  gramps/plugins/webreport/family.py
  gramps/plugins/webreport/media.py
  gramps/plugins/webreport/narrativeweb.py
  gramps/plugins/webreport/person.py
  gramps/plugins/webreport/place.py
  gramps/plugins/webreport/repository.py
  gramps/plugins/webreport/source.py
  gramps/plugins/webreport/surname.py
  gramps/plugins/webreport/surnamelist.py
  gramps/plugins/webreport/thumbnail.py
Labels: bug, enhancement

#1559 Set filter editor rule list to expand
  gramps/gui/editors/filtereditor.py
Labels: bug

#1560 Change the subscript key binding in the note editor
  gramps/gui/widgets/styledtexteditor.py
Labels: bug

#1561 Refresh row in Addon Manager after an addon is installed
  gramps/gui/plug/_windows.py
Labels: bug
