Repository gramps-project/gramps, pull requests merged in 2023-07, with the labels that each got.

#1163 Calendarreport
  gramps/plugins/drawreport/calendarreport.py
Labels: enhancement, Approved

#1371 Use ObjEntry to select a person as an association
  gramps/gui/editors/editpersonref.py
  gramps/gui/editors/objectentries.py
  gramps/gui/glade/editpersonref.glade
Labels: enhancement, Approved

#1399 Add option to hide ages for events after death
  gramps/gen/config.py
  gramps/gui/configure.py
  gramps/gui/editors/displaytabs/eventrefmodel.py
  gramps/gui/editors/editperson.py
Labels: enhancement

#1360 Remove unused constant ENV_DIR
  gramps/cli/argparser.py
  gramps/gen/const.py
Labels: Code Quality

#1361 Geography: Use path from constants
  gramps/plugins/lib/maps/geography.py
Labels: Code Quality

#1368 Support XDG base directory specification
  gramps/cli/argparser.py
  gramps/gen/config.py
  gramps/gen/const.py
  gramps/gen/plug/report/_book.py
  gramps/gen/plug/report/_options.py
  gramps/gen/recentfiles.py
  gramps/grampsapp.py
  gramps/gui/configure.py
  gramps/gui/viewmanager.py
  gramps/plugins/lib/maps/constants.py
  gramps/plugins/lib/maps/geography.py
  gramps/plugins/tool/verify.py
  gramps/plugins/webstuff/webstuff.py
Labels: enhancement

#1384 XDG MIME types improvements
  data/org.gramps_project.Gramps.xml.in
Labels: enhancement

#1364 Spelling: "vCard" in importvcard.py
  gramps/plugins/importer/importvcard.py
Labels: enhancement

#1373 Update web reports cc copyright version to 4.0
  gramps/plugins/lib/libhtmlconst.py
Labels: enhancement

#1388 Add .venv environments
  .gitignore
Labels: enhancement

#1400 Add new gender option of "Other"
  data/css/ancestortree.css
  data/tests/imp_sample.gramps
  gramps/gen/config.py
  gramps/gen/filters/rules/person/__init__.py
  gramps/gen/filters/rules/person/_hasothergender.py
  gramps/gen/lib/genderstats.py
  gramps/gen/lib/person.py
  gramps/gen/plug/docgen/treedoc.py
  gramps/gen/utils/string.py
  gramps/gen/utils/symbols.py
  gramps/gen/utils/unknown.py
  gramps/gui/configure.py
  gramps/gui/editors/editperson.py
  gramps/gui/filters/sidebar/_personsidebarfilter.py
  gramps/gui/merge/mergeperson.py
  gramps/gui/utils.py
  gramps/gui/views/treemodels/peoplemodel.py
  gramps/gui/widgets/fanchart.py
  gramps/plugins/db/dbapi/test/db_test.py
  gramps/plugins/drawreport/statisticschart.py
  gramps/plugins/export/exportcsv.py
  gramps/plugins/export/exportgedcom.py
  gramps/plugins/export/exportvcard.py
  gramps/plugins/export/exportxml.py
  gramps/plugins/gramplet/statsgramplet.py
  gramps/plugins/graph/gvfamilylines.py
  gramps/plugins/graph/gvhourglass.py
  gramps/plugins/graph/gvrelgraph.py
  gramps/plugins/importer/importcsv.py
  gramps/plugins/importer/importvcard.py
  gramps/plugins/importer/importxml.py
  gramps/plugins/lib/libgedcom.py
  gramps/plugins/lib/libnarrate.py
  gramps/plugins/quickview/filterbyname.py
  gramps/plugins/test/tools_test.py
  gramps/plugins/textreport/familygroup.py
  gramps/plugins/textreport/indivcomplete.py
  gramps/plugins/textreport/summary.py
  gramps/plugins/tool/testcasegenerator.py
  gramps/plugins/tool/verify.py
  gramps/plugins/webreport/person.py
  gramps/plugins/webreport/statistics.py
  images/webstuff/Web_Gender_Other.png
  po/POTFILES.in
Labels: enhancement

#1266 Note editor enhancements
  gramps/gen/lib/styledtexttagtype.py
  gramps/gui/widgets/styledtextbuffer.py
  gramps/gui/widgets/styledtexteditor.py
Labels: enhancement

#1124 Added support for open spans.
  gramps/gen/datehandler/_date_ar.py
  gramps/gen/datehandler/_date_bg.py
  gramps/gen/datehandler/_date_ca.py
  gramps/gen/datehandler/_date_cs.py
  gramps/gen/datehandler/_date_da.py
  gramps/gen/datehandler/_date_de.py
  gramps/gen/datehandler/_date_el.py
  gramps/gen/datehandler/_date_es.py
  gramps/gen/datehandler/_date_fi.py
  gramps/gen/datehandler/_date_fr.py
  gramps/gen/datehandler/_date_hr.py
  gramps/gen/datehandler/_date_hu.py
  gramps/gen/datehandler/_date_is.py
  gramps/gen/datehandler/_date_it.py
  gramps/gen/datehandler/_date_ja.py
  gramps/gen/datehandler/_date_lt.py
  gramps/gen/datehandler/_date_nb.py
  gramps/gen/datehandler/_date_nl.py
  gramps/gen/datehandler/_date_pl.py
  gramps/gen/datehandler/_date_pt.py
  gramps/gen/datehandler/_date_ru.py
  gramps/gen/datehandler/_date_sk.py
  gramps/gen/datehandler/_date_sl.py
  gramps/gen/datehandler/_date_sr.py
  gramps/gen/datehandler/_date_sv.py
  gramps/gen/datehandler/_date_uk.py
  gramps/gen/datehandler/_date_zh_CN.py
  gramps/gen/datehandler/_date_zh_TW.py
  gramps/gen/datehandler/_datedisplay.py
  gramps/gen/datehandler/_dateparser.py
  gramps/gen/datehandler/_datestrings.py
  gramps/gen/datehandler/test/datehandler_test.py
  gramps/gen/lib/date.py
  gramps/gen/lib/test/date_test.py
  gramps/gui/editors/editdate.py
  gramps/plugins/export/exportgeneweb.py
  gramps/plugins/export/exportvcalendar.py
  gramps/plugins/export/exportvcard.py
  gramps/plugins/export/exportxml.py
  gramps/plugins/importer/importgeneweb.py
  gramps/plugins/importer/importxml.py
  gramps/plugins/lib/libgedcom.py
Labels: enhancement, Documentation, Approved

#1263 Image Meta Viewer - expand support for IPTC, XMP and Named regions with Thumbnails
  example/gramps/O0.jpg
  example/gramps/O2.jpg
  example/gramps/O3.jpg
  example/gramps/O4.jpg
  example/gramps/O5.jpg
  example/gramps/image_credits.md
  gramps/plugins/lib/libmetadata.py
Labels: enhancement, Needs Testing, Approved

#1451 Add extra plugin properties
  gramps/gen/plug/_pluginreg.py
Labels: enhancement

#1450 Port from GtkSpell to Gspell
  README.md
  docs/coregui/gui_widgets.rst
  gramps/gen/utils/grampslocale.py
  gramps/grampsapp.py
  gramps/gui/configure.py
  gramps/gui/spell.py
  gramps/gui/widgets/styledtextbuffer.py
  gramps/gui/widgets/styledtexteditor.py
Labels: enhancement

#1454 Weblate translator requested updates to source strings
  gramps/grampsapp.py
  gramps/plugins/gramplet/welcomegramplet.py
  gramps/plugins/graph/gvhourglass.py
  gramps/plugins/lib/maps/geography.py
  gramps/plugins/lib/maps/osmgps.py
  gramps/plugins/tool/reorderids.glade
  gramps/plugins/webreport/basepage.py
  gramps/plugins/webreport/webcal.py
  po/gramps.pot
Labels: Translation

#1448 Color values in the range [0-1] are supposed to be floats
  gramps/gui/utils.py
Labels: bug

#1452 grampslocale: Remove unused member variables
  gramps/gen/utils/grampslocale.py
  gramps/gen/utils/maclocale.py
  gramps/grampsapp.py
Labels: Code Quality

#1443 allow build on windows
  setup.py
Labels: bug

#1460 Fix garbage collection issue in UIManager
  gramps/gui/uimanager.py
Labels: bug

#1461 Avoid signal warning during editor clean up
  gramps/gui/editors/displaytabs/gallerytab.py
Labels: bug

#1372 SrcAttribute object has no attribute has_citations
  gramps/gui/editors/displaytabs/attrmodel.py
Labels: bug, enhancement

#1465 Fix garbage collection issue in Callback
  gramps/gen/utils/callback.py
Labels: bug

#1462 Fix display warnings in unit tests
  .github/workflows/gramps-ci.yml
Labels: enhancement

#1464 Migrate build from distutils to setuptools
  setup.py
Labels: enhancement

#1310 Added fliptext feature to Fan Chart Report
  gramps/plugins/drawreport/fanchart.py
Labels: enhancement, string

#1172 Display a tooltip warning if a window saves data immediately
  gramps/gen/config.py
  gramps/gui/clipboard.py
  gramps/gui/configure.py
  gramps/gui/editors/filtereditor.py
  gramps/gui/views/tags.py
Labels: enhancement

#1339 Add option for added symbol on Hourglass Report
  gramps/plugins/graph/gvhourglass.py
Labels: enhancement, string

#1342 Common calendar on Statistics chart
  gramps/plugins/drawreport/statisticschart.py
Labels: bug

#1375 Improvement: Add stock_category_icon support
  gramps/gen/plug/_pluginreg.py
  gramps/gui/navigator.py
Labels: enhancement

#1378 Improvement: Add optional support for comments section at top of ini in the save method
  gramps/gen/test/config_test.py
  gramps/gen/utils/configmanager.py
Labels: enhancement

#1382 Narweb: clarify how to get the API_KEY
  gramps/plugins/webreport/narrativeweb.py
Labels: enhancement, string

#1383 Add the possibility to search sensitive/insensitive
  gramps/gen/filters/_filterlist.py
  gramps/gen/filters/_filterparser.py
  gramps/gen/filters/rules/_hasnotebase.py
  gramps/gen/filters/rules/_rule.py
  gramps/gui/editors/filtereditor.py
  gramps/gui/filters/sidebar/_citationsidebarfilter.py
  gramps/gui/filters/sidebar/_eventsidebarfilter.py
  gramps/gui/filters/sidebar/_familysidebarfilter.py
  gramps/gui/filters/sidebar/_mediasidebarfilter.py
  gramps/gui/filters/sidebar/_notesidebarfilter.py
  gramps/gui/filters/sidebar/_personsidebarfilter.py
  gramps/gui/filters/sidebar/_placesidebarfilter.py
  gramps/gui/filters/sidebar/_reposidebarfilter.py
  gramps/gui/filters/sidebar/_sidebarfilter.py
  gramps/gui/filters/sidebar/_sourcesidebarfilter.py
Labels: enhancement, string

#1397 Narweb: Sort events by date in the individual page.
  gramps/plugins/webreport/basepage.py
  gramps/plugins/webreport/person.py
Labels: enhancement

#1438 Add coordinates format with description.
  gramps/gen/config.py
  gramps/gen/plug/report/stdoptions.py
  gramps/gen/utils/place.py
  gramps/gui/configure.py
Labels: enhancement, string

#1442 Found some problems after commit 35f20a88
  gramps/plugins/webreport/basepage.py
  gramps/plugins/webreport/common.py
  gramps/plugins/webreport/place.py
Labels: bug

#1470 Fix garbage collection issue in ConfigManager
  gramps/gen/utils/configmanager.py
  gramps/gui/widgets/grampletbar.py
  gramps/gui/widgets/grampletpane.py
Labels: bug

#1445 Birthday and Anniversary Report: add person ID
  gramps/plugins/textreport/birthdayreport.py
Labels: enhancement

#1467 Enhance Date Parser Display Test debug tool
  gramps/plugins/tool/dateparserdisplaytest.py
Labels: enhancement

#1472 Translations update from Hosted Weblate
  po/ar.po
  po/bg.po
  po/br.po
  po/ca.po
  po/cs.po
  po/da.po
  po/de.po
  po/de_AT.po
  po/el.po
  po/en_GB.po
  po/eo.po
  po/es.po
  po/fa.po
  po/fi.po
  po/fr.po
  po/ga.po
  po/gl.po
  po/he.po
  po/hr.po
  po/hu.po
  po/id.po
  po/is.po
  po/it.po
  po/ja.po
  po/lt.po
  po/mk.po
  po/nb.po
  po/nl.po
  po/nn.po
  po/pl.po
  po/pt_BR.po
  po/pt_PT.po
  po/ro.po
  po/ru.po
  po/sk.po
  po/sl.po
  po/sq.po
  po/sr.po
  po/sr_Latn.po
  po/sv.po
  po/ta.po
  po/tr.po
  po/uk.po
  po/vi.po
  po/zh_CN.po
  po/zh_HK.po
  po/zh_TW.po
Labels: Translation

#1318 Display leap day anniversaries every year on calendars
  gramps/gen/config.py
  gramps/gen/lib/date.py
  gramps/gen/lib/test/date_test.py
  gramps/gui/configure.py
  gramps/plugins/drawreport/calendarreport.py
  gramps/plugins/textreport/birthdayreport.py
  gramps/plugins/webreport/calendar.py
  gramps/plugins/webreport/webcal.py
Labels: enhancement, string

#1471 New JJ/MM/AAAA French Date Format
  gramps/gen/datehandler/_date_fr.py
Labels: enhancement

#1455 Fix first name format for genealogytree docgen
  gramps/gen/plug/docgen/treedoc.py
  gramps/gui/plug/report/_treereportdialog.py
Labels: bug

#1441 Add a new primary surname substitution keyword option
  gramps/gen/lib/surnamebase.py
  gramps/plugins/lib/libsubstkeyword.py
Labels: enhancement, string

#1425 Pylint cleanups and minor optimizations for gen.utils.db
  gramps/gen/utils/db.py
Labels: Code Quality

#1474 Add new note type of "Analysis"
  gramps/gen/lib/notetype.py
Labels: enhancement

#1390 Improvement: Add bookmark-list-changed support
  gramps/gen/db/bookmarks.py
  gramps/gen/db/dummydb.py
  gramps/gen/db/generic.py
Labels: enhancement

#1312 Create new Addon Manager dialog
  data/gramps.css
  gramps/gen/config.py
  gramps/gen/plug/__init__.py
  gramps/gen/plug/_manager.py
  gramps/gen/plug/_pluginreg.py
  gramps/gen/plug/utils.py
  gramps/gen/utils/requirements.py
  gramps/gui/configure.py
  gramps/gui/displaystate.py
  gramps/gui/grampsgui.py
  gramps/gui/plug/_windows.py
  gramps/gui/viewmanager.py
  images/hicolor/16x16/actions/gramps-addon.png
  images/hicolor/22x22/actions/gramps-addon.png
  images/hicolor/24x24/actions/gramps-addon.png
  images/hicolor/48x48/actions/gramps-addon.png
  images/hicolor/scalable/actions/gramps-addon.svg
  po/POTFILES.in
  setup.py
Labels: enhancement, string

#1402 Add support for CITE plugins
  gramps/gen/config.py
  gramps/gen/plug/_manager.py
  gramps/gen/plug/_pluginreg.py
  gramps/gen/plug/report/endnotes.py
  gramps/gen/plug/utils.py
  gramps/gui/configure.py
  gramps/plugins/cite/__init__.py
  gramps/plugins/cite/cite.gpr.py
  gramps/plugins/cite/default.py
  po/POTFILES.in
  po/POTFILES.skip
Labels: enhancement, string

#1416 Backup: Add a popup to show the gramps state
  gramps/gui/utils.py
  gramps/gui/viewmanager.py
Labels: bug, enhancement, string

#1391 Improvement: Add citation_list to event references
  data/grampsxml.dtd
  data/grampsxml.rng
  example/gramps/example.gramps
  gramps/gen/db/upgrade.py
  gramps/gen/lib/eventref.py
  gramps/gui/editors/editeventref.py
  gramps/plugins/export/exportxml.py
  gramps/plugins/importer/importxml.py
  gramps/plugins/test/tools_test.py
Labels: enhancement

#1478 Use XDG pictures directory as the default media path
  gramps/gen/const.py
  gramps/gen/utils/file.py
  gramps/gen/utils/test/file_test.py
Labels: bug

#1479 Allow custom undo managers in database plugins
  gramps/gen/db/generic.py
  gramps/gen/db/undoredo.py
Labels: enhancement
