Repository gramps-project/gramps, pull requests merged in 2024-05, with the labels that each got.

#1710 Prevent hyperlink tagging being added as an undo action
  gramps/gui/widgets/undoablestyledbuffer.py
Labels: bug

#1712 URL-Encode paths when creating URLs to pass to Gio.AppInfo.launch_default_for_uri.
  gramps/gui/utils.py
Labels: bug

#1714 Remove the spaces padding the connector in a hyphenated surname
  gramps/gen/display/name.py
Labels: bug

#1716 Fix missing media in narrative web report person pages
  gramps/plugins/webreport/basepage.py
Labels: bug

#1503 Some pylint cleanups for gramps/gen/plug/*.py
  gramps/gen/plug/_gramplet.py
  gramps/gen/plug/_manager.py
  gramps/gen/plug/_options.py
  gramps/gen/plug/_pluginreg.py
  gramps/gen/plug/_thumbnailer.py
  gramps/gen/plug/utils.py
Labels: Code Quality

#1529 Pylint cleanups for gen/db/*.py
  gramps/gen/db/base.py
  gramps/gen/db/dummydb.py
  gramps/gen/db/generic.py
  gramps/gen/db/txn.py
  gramps/gen/db/undoredo.py
  gramps/gen/db/utils.py
Labels: Code Quality

#1676 Add forwards and backwards navigation using mouse buttons.
  gramps/gui/views/navigationview.py
  gramps/gui/views/pageview.py
Labels: enhancement

#1699 Use preferred name instead of default name in name editor
  gramps/gui/editors/displaytabs/nameembedlist.py
Labels: enhancement

#1705 Change the output of ADDR tags in the Gedcom export
  data/tests/exp_sample_ged.ged
  gramps/gen/lib/locationbase.py
  gramps/plugins/export/exportgedcom.py
Labels: enhancement

#1706 Add support for ISO 639-3 part 3 standard language code
  README.md
  aio/build.sh
  gramps/gui/editors/editplacename.py
Labels: enhancement

#1711 Replace deprecated Gtk[HV]Box with GtkBox
  gramps/plugins/docgen/gtkprint.glade
Labels: Code Quality

#1715 Add new role types present in the Gedcom 7.0 specification
  gramps/gen/lib/eventroletype.py
  gramps/plugins/test/tools_test.py
Labels: enhancement

#1533 Some filter rule type related cleanups
  gramps/gen/filters/rules/_hasattributebase.py
  gramps/gen/filters/rules/_haseventbase.py
  gramps/gen/filters/rules/event/_hasdata.py
  gramps/gen/filters/rules/event/_hastype.py
  gramps/gen/filters/rules/family/_hasreltype.py
  gramps/gen/filters/rules/note/_hasnote.py
  gramps/gen/filters/rules/note/_hastype.py
  gramps/gen/filters/rules/person/_hasevent.py
  gramps/gen/filters/rules/person/_hasfamilyevent.py
  gramps/gen/filters/rules/person/_hasnameorigintype.py
  gramps/gen/filters/rules/person/_hasnametype.py
  gramps/gen/filters/rules/person/_hasrelationship.py
  gramps/gen/filters/rules/person/_hassoundexname.py
  gramps/gen/filters/rules/person/_iswitness.py
  gramps/gen/filters/rules/place/_hasdata.py
  gramps/gen/filters/rules/repository/_hasrepo.py
Labels: Code Quality
