Repository gramps-project/gramps, pull requests merged in 2024-07, with the labels that each got.

#1718 Fix error when changing the style of misspelt words
  gramps/gui/widgets/styledtextbuffer.py
Labels: bug

#1720 Check that pdf output file exists in genealogy tree reports
  gramps/gen/plug/docgen/treedoc.py
Labels: bug

#1732 Fix NoteType values in CSV import
  gramps/plugins/importer/importcsv.py
Labels: bug

#1735 Disable rounding glyph positions in cairo document generator
  gramps/plugins/docgen/cairodoc.py
Labels: bug

#1728 Fix fallback for the `image_size` utility function
  gramps/gen/utils/image.py
Labels: bug

#1742 Translations update from Hosted Weblate
  po/nb.po
Labels: Translation

#1737 Fix PDF generation failure with LaTeX-based reports
  gramps/gen/plug/docgen/treedoc.py
Labels: bug

#1739 Clarified terminology for father/mother lineage description
  gramps/plugins/quickview/lineage.py
Labels: bug

#1745 Improve media performance in the narrative web report
  gramps/plugins/webreport/media.py
Labels: bug

#1741 Update aboutdialog.py fix linkrot
  gramps/gui/aboutdialog.py
Labels: Documentation
