Repository gramps-project/gramps, pull requests merged in 2024-04, with the labels that each got.

#1694 Narweb: Person object has no get_father_handle
  gramps/plugins/webreport/narrativeweb.py
Labels: bug

#1695 Hebrew relationship calculator not loading after v5.2 was released
  gramps/plugins/rel/relplugins.gpr.py
Labels: bug

#1660 Use regular buttons to copy owner information from/to preferences
  gramps/plugins/tool/ownereditor.glade
  gramps/plugins/tool/ownereditor.py
Labels: enhancement

#1661 Replace GtkArrow with GtkImage and symbolic icons
  gramps/gui/widgets/expandcollapsearrow.py
  gramps/plugins/view/relview.py
Labels: Code Quality

#1663 Replace GtkMenu with GioMenu in Gramplets bar
  gramps/gui/widgets/grampletbar.py
Labels: Code Quality

#1665 Replace GtkMenu with GioMenu in DropdownSidebar
  gramps/plugins/sidebar/dropdownsidebar.py
Labels: Code Quality

#1666 Remove unused Subversion keyword substitutions
  data/css/Web_Basic-Blue.css
  data/css/Web_Vertical-Menus.css
  data/css/ancestortree.css
  gramps/gen/datehandler/_date_hr.py
  gramps/gui/navigator.py
  gramps/plugins/sidebar/dropdownsidebar.py
  gramps/plugins/sidebar/expandersidebar.py
  po/ca.po
  po/pl.po
Labels: Code Quality

#1675 Sort AIO prerequisites + remove unneeded
  aio/build.sh
Labels: Code Quality

#1678 Allow 0 ancestors/descendants in hourglass graph
  gramps/plugins/graph/gvhourglass.py
Labels: enhancement

#1702 Change repository "Title" to "Name" in the source editor
  gramps/gui/editors/displaytabs/repoembedlist.py
Labels: bug

#1528 Pylint cleanups for plugins/db/dbapi/*.py
  gramps/gen/db/base.py
  gramps/plugins/db/dbapi/dbapi.py
  gramps/plugins/db/dbapi/sqlite.py
Labels: Code Quality
