Repository gramps-project/gramps, pull requests merged in 2024-03, with the labels that each got.

#1659 Fix filter rules missing the use_case parameter
  gramps/gen/filters/rules/_hastextmatchingregexpof.py
  gramps/gen/filters/rules/person/_hascommonancestorwithfiltermatch.py
  gramps/gen/filters/rules/person/_hasgallery.py
  gramps/gen/filters/rules/person/_hastextmatchingregexpof.py
Labels: bug

#1657 Update AppStream MetaInfo file to conform to latest spec
  data/org.gramps_project.Gramps.metainfo.xml.in
  po/its/appdata.its
  po/its/appdata.loc
  po/its/metainfo.its
  po/its/metainfo.loc
Labels: enhancement

#1668 Fix display of invalid dates in editor citation tabs
  gramps/gui/editors/displaytabs/citationrefmodel.py
Labels: bug

#1669 Addon Manager Requirements mark symbols on Mac
  gramps/gen/utils/requirements.py
  gramps/gui/configure.py
Labels: bug

#1672 Fix unit tests when run with Python 3.12
  gramps/plugins/db/dbapi/dbapi.py
  gramps/plugins/importer/importgedcom.py
  gramps/plugins/importer/importprogen.py
Labels: bug

#1679 Update AIO minimum Windows version requirement to 8.1 64-bit
  aio/grampsaio64.nsi.template
Labels: bug

#1680 Fix the addon translator language for core translations
  gramps/gen/utils/grampslocale.py
Labels: bug

#1681 Fix place title when place names use open spans
  gramps/gen/utils/location.py
Labels: bug

#1683 Cannot create Place with coordinates via Geography
  gramps/plugins/lib/maps/geography.py
Labels: bug

#1684 Fix the Tag.is_empty() method
  gramps/gen/lib/tag.py
Labels: bug

#1670 Fix fan charts on HiDPI screens
  gramps/gui/widgets/fanchart.py
  gramps/gui/widgets/fanchart2way.py
  gramps/gui/widgets/fanchartdesc.py
Labels: bug

#1686 Tidy up the README file
  README.md
Labels: Documentation

#1687 Allow experimental and beta plugins to be registered
  gramps/gen/plug/_pluginreg.py
Labels: bug

#1690 Fix error when installing an addon that will not be registered
  gramps/gui/plug/_windows.py
Labels: bug
