Repository gramps-project/gramps, pull requests merged in 2024-02, with the labels that each got.

#1597 Use imagesize rather than magic
  README.md
  gramps/gen/utils/image.py
Labels: bug

#1600 Fix GEDCOM import for SUBN record containing note
  data/tests/imp_sample.gramps
  gramps/plugins/lib/libgedcom.py
Labels: bug

#1602 sort Confidence col in Source Citations tabs
  gramps/gui/editors/displaytabs/citationembedlist.py
  gramps/gui/editors/displaytabs/citationrefmodel.py
Labels: bug, Translation, string

#1603 Fix bug in narrative web when the role name contains a dash
  gramps/plugins/webreport/basepage.py
Labels: bug

#1604 Add event reference citations to the complete individual report
  gramps/plugins/textreport/indivcomplete.py
Labels: bug

#1605 Fix display of gramplet help URLs that start with "https://"
  gramps/gui/widgets/grampletbar.py
  gramps/gui/widgets/grampletpane.py
Labels: bug

#1608 New Citations not included on the Narrative Web - Re: Add citations to event references
  gramps/gen/proxy/private.py
  gramps/plugins/webreport/basepage.py
  gramps/plugins/webreport/narrativeweb.py
Labels: bug, enhancement

#1610 Added option to display birth and death info in descendant report
  gramps/plugins/textreport/descendreport.py
Labels: enhancement

#1613 Fix context menu in all family events quick view screen
  gramps/plugins/quickview/all_events.py
Labels: bug

#1615 Allow user to round or not the year when display age precision is "Years"
  gramps/gen/config.py
  gramps/gen/lib/date.py
  gramps/gui/configure.py
Labels: bug

#1618 Fixes hyphenated surnames in name displayer
  gramps/gen/display/name.py
Labels: bug

#1622 importgeneweb.py broken with Python 3.11
  gramps/plugins/importer/importgeneweb.py
Labels: bug

#1624 Fix DeprecationWarning for invalid escape sequence
  gramps/grampsapp.py
Labels: Code Quality

#1625 Report simpler Python version string in About and Error dialogs
  gramps/gui/aboutdialog.py
  gramps/gui/logger/_errorreportassistant.py
Labels: bug

#1626 Clarify that tip applies only to "Grouped People View"
  data/tips.xml
Labels: bug

#1628 Fix gramps example media source
  example/gramps/example.gramps
Labels: bug

#1629 Update and fix CSV import
  gramps/plugins/importer/importcsv.py
Labels: bug

#1631 Changing -f gramps-xml to -f gramps (Issue ID 0009723)
  data/man/en.rst
  gramps/cli/argparser.py
Labels: bug

#1634 Added HasRepo rule to rule list
  gramps/gen/filters/rules/repository/__init__.py
Labels: bug

#1632 Fix command line progress output
  gramps/cli/test/user_test.py
  gramps/cli/user.py
Labels: bug

#1639 Fix invalid escape sequences
  aio/grampsaioc.py
  aio/grampsaiocd.py
  aio/grampsaiow.py
  gramps/gen/datehandler/_date_he.py
  gramps/gen/plug/docgen/treedoc.py
  gramps/gen/utils/resourcepath.py
Labels: bug

#1644 Fix Windows AIO build
  aio/build.sh
  aio/grampsaio64.nsi.template
Labels: bug

#1650 Emit a "plugins-reloaded" signal when a new addon is installed
  gramps/gui/plug/_windows.py
Labels: bug

#1652 Remove the Trove classifier "Natural Language :: German(Austrian)"
  setup.py
Labels: bug

#1653 Translations update from Hosted Weblate
  po/it.po
Labels: Translation

#1654 Translations update from Hosted Weblate
  po/zh_CN.po
Labels: Translation
