Repository gramps-project/gramps, pull requests merged in 2024-12, with the labels that each got.

#1786 Switch from pickled blobs to JSON data
  gramps/gen/db/conversion_tools/__init__.py
  gramps/gen/db/conversion_tools/conversion_21.py
  gramps/gen/db/generic.py
  gramps/gen/db/upgrade.py
  gramps/gen/display/name.py
  gramps/gen/filters/_genericfilter.py
  gramps/gen/lib/date.py
  gramps/gen/lib/grampstype.py
  gramps/gen/lib/note.py
  gramps/gen/lib/researcher.py
  gramps/gen/lib/serialize.py
  gramps/gen/lib/styledtext.py
  gramps/gen/lib/test/serialize_test.py
  gramps/gen/merge/diff.py
  gramps/gui/editors/editsecondary.py
  gramps/gui/plug/quick/_quicktable.py
  gramps/gui/views/treemodels/citationbasemodel.py
  gramps/gui/views/treemodels/citationtreemodel.py
  gramps/gui/views/treemodels/eventmodel.py
  gramps/gui/views/treemodels/familymodel.py
  gramps/gui/views/treemodels/mediamodel.py
  gramps/gui/views/treemodels/notemodel.py
  gramps/gui/views/treemodels/peoplemodel.py
  gramps/gui/views/treemodels/placemodel.py
  gramps/gui/views/treemodels/repomodel.py
  gramps/gui/views/treemodels/sourcemodel.py
  gramps/plugins/db/bsddb/bsddb.py
  gramps/plugins/db/dbapi/dbapi.py
  gramps/plugins/db/dbapi/sqlite.py
  gramps/plugins/gramplet/sessionloggramplet.py
  gramps/plugins/importer/importvcard.py
  gramps/plugins/importer/importxml.py
  gramps/plugins/lib/libgedcom.py
  gramps/plugins/lib/libmixin.py
  gramps/plugins/lib/libprogen.py
  gramps/plugins/test/imports_test.py
  gramps/plugins/test/tools_test.py
  gramps/plugins/tool/check.py
  gramps/plugins/tool/mediamanager.py
  gramps/plugins/tool/rebuildgenderstat.py
  test/blob_to_json_test.py
Labels: enhancement

#1755 Restore AIO console executable's icon
  aio/setup.py
Labels: bug

#1762 Render reports with styled notes containing subscript and strikethrough
  gramps/gen/plug/docbackend/cairobackend.py
  gramps/gen/plug/docbackend/docbackend.py
  gramps/plugins/docgen/latexdoc.py
  gramps/plugins/docgen/odfdoc.py
  gramps/plugins/lib/libhtmlbackend.py
  gramps/plugins/lib/libodfbackend.py
Labels: bug

#1770 Fix printing of Books
  gramps/gui/plug/report/_bookdialog.py
Labels: bug

#1778 "Age on date": correct misleading description of GUI element placement
  gramps/plugins/gramplet/ageondategramplet.py
Labels: bug

#1780 Fix list size option in the top surnames gramplet
  gramps/plugins/gramplet/topsurnamesgramplet.py
Labels: bug

#1784 Downgrade informational messages from warning level
  gramps/gen/config.py
Labels: bug

#1804 Gramps version output now reports OS rather than Platform
  gramps/grampsapp.py
Labels: bug

#1773 Correct documentation for Date.match()
  gramps/gen/lib/date.py
Labels: Documentation

#1758 Fix unicode conversion bug when upgrading from schema 16 to 17
  gramps/gen/db/upgrade.py
Labels: bug

#1772 Fix Date sortval bug and corresponding unit test
  gramps/gen/lib/date.py
  gramps/gen/lib/test/date_test.py
Labels: bug

#1774 Probably alive should use today when the current date is empty
  gramps/gen/utils/alive.py
Labels: bug

#1824 Added a dict wrapper that acts like an object
  gramps/gen/lib/serialize.py
  gramps/gen/lib/test/serialize_test.py
Labels: enhancement

#1761 Clean up `exec` and `globals`
  gramps/gen/display/name.py
  gramps/gen/plug/utils.py
  gramps/plugins/test/db_undo_and_signals_test.py
  gramps/plugins/tool/removeunused.py
  gramps/plugins/tool/verify.py
Labels: bug, Code Quality
