Repository gramps-project/gramps, pull requests merged in 2025-01, with the labels that each got.

#1759 Use contextlib to redirect stdout/stderr
  gramps/plugins/gramplet/eval.py
Labels: Code Quality

#1760 Simplify multiple calls to str.startswith / str.endswith
  gramps/gen/plug/utils.py
  gramps/gen/utils/grampslocale.py
  gramps/gui/plug/_windows.py
  gramps/plugins/lib/libgedcom.py
  gramps/plugins/webreport/basepage.py
  gramps/plugins/webreport/calendar.py
  gramps/plugins/webreport/common.py
  gramps/plugins/webreport/webcal.py
  gramps/test/test_util.py
  po/update_po.py
Labels: Code Quality

#1763 Fix Python 3.12 deprecation warnings
  gramps/grampsapp.py
  gramps/gui/aboutdialog.py
  gramps/gui/logger/_errorreportassistant.py
  gramps/gui/uimanager.py
  gramps/plugins/db/dbapi/sqlite.py
Labels: Code Quality

#1764 Replace deprecated Gdk.Color by Gdk.RGBA
  gramps/gui/configure.py
  gramps/gui/plug/report/_styleeditor.py
  gramps/plugins/lib/maps/datelayer.py
  gramps/plugins/lib/maps/kmllayer.py
  gramps/plugins/lib/maps/lifewaylayer.py
  gramps/plugins/lib/maps/markerlayer.py
  gramps/plugins/lib/maps/messagelayer.py
  gramps/plugins/view/geomoves.py
Labels: Code Quality

#1771 Use standard decorator form of defining properties
  gramps/gen/plug/_pluginreg.py
  gramps/gui/glade.py
  gramps/gui/plug/_windows.py
  gramps/plugins/lib/libhtml.py
Labels: Code Quality

#1633 Show other roles for an event in the narrative web report
  gramps/gen/utils/db.py
  gramps/plugins/webreport/basepage.py
  gramps/plugins/webreport/narrativeweb.py
Labels: enhancement

#1506 Changed layout of places and dates in familylines plugin
  gramps/plugins/graph/gvfamilylines.py
Labels: enhancement

#1756 Add rule 'having note of type' for citation, event, family, person, p…
  gramps/gen/filters/rules/_hasnotetypebase.py
  gramps/gen/filters/rules/citation/__init__.py
  gramps/gen/filters/rules/citation/_hasnotetype.py
  gramps/gen/filters/rules/event/__init__.py
  gramps/gen/filters/rules/event/_hasnotetype.py
  gramps/gen/filters/rules/family/__init__.py
  gramps/gen/filters/rules/family/_hasnotetype.py
  gramps/gen/filters/rules/person/__init__.py
  gramps/gen/filters/rules/person/_hasnotetype.py
  gramps/gen/filters/rules/place/__init__.py
  gramps/gen/filters/rules/place/_hasnotetype.py
  gramps/gen/filters/rules/source/__init__.py
  gramps/gen/filters/rules/source/_hasnotetype.py
  po/POTFILES.in
Labels: enhancement

#1721 Enhanced version of the Filter gramplet
  data/gramps.css
  gramps/gen/filters/rules/event/__init__.py
  gramps/gen/filters/rules/event/_hasevent.py
  gramps/gen/filters/rules/source/__init__.py
  gramps/gen/filters/rules/source/_hassource.py
  gramps/gui/filters/sidebar/_citationsidebarfilter.py
  gramps/gui/filters/sidebar/_personsidebarfilter.py
  gramps/gui/filters/sidebar/_sidebarfilter.py
  po/POTFILES.in
Labels: enhancement

#1729 Fix unittest for local timezones
  gramps/plugins/test/exports_test.py
Labels: enhancement

#1731 Skip TestImports if en_US locale is not available on build host
  gramps/plugins/test/imports_test.py
Labels: enhancement

#1730 Replace deprecated makeSuite with TestLoader().loadTestsFromTestCase
  test/GrampsLogger/ErrorReportAssistant_Test.py
  test/GrampsLogger/GtkHandler_Test.py
Labels: Code Quality

#1825 Teach GrampsType.set() to work with a dict
  gramps/gen/lib/grampstype.py
  gramps/gui/views/treemodels/eventmodel.py
  gramps/gui/views/treemodels/familymodel.py
  gramps/gui/views/treemodels/notemodel.py
  gramps/gui/views/treemodels/placemodel.py
  gramps/gui/views/treemodels/repomodel.py
Labels: bug, ready-to-merge

#1834 Fix error in Fast*Filter
  gramps/gui/editors/editfamily.py
Labels: bug-fix

#1838 Fix scroll direction in pedigree view
  gramps/plugins/view/pedigreeview.py
Labels: bug

#1803 Fix exception when finding relationship to home person
  gramps/plugins/quickview/all_relations.py
Labels: bug

#1844 Fix Citations gramplet to recognize event reference citations
  gramps/plugins/gramplet/citations.py
Labels: bug

#1845 Fix German date handler for reports
  gramps/gen/datehandler/_date_de.py
Labels: bug

#1847 Update list of incomplete translations
  gramps/gen/utils/grampslocale.py
Labels: Translation

#1849 Translations update from Hosted Weblate
  po/ar.po
  po/bg.po
  po/br.po
  po/ca.po
  po/cs.po
  po/da.po
  po/de.po
  po/de_AT.po
  po/el.po
  po/en_GB.po
  po/eo.po
  po/es.po
  po/fa.po
  po/fi.po
  po/fr.po
  po/ga.po
  po/gl.po
  po/he.po
  po/hr.po
  po/hu.po
  po/id.po
  po/is.po
  po/it.po
  po/ja.po
  po/ko.po
  po/lt.po
  po/mk.po
  po/nb.po
  po/nl.po
  po/nn.po
  po/pl.po
  po/pt_BR.po
  po/pt_PT.po
  po/ro.po
  po/ru.po
  po/sk.po
  po/sl.po
  po/sq.po
  po/sr.po
  po/sr_Latn.po
  po/sv.po
  po/ta.po
  po/tr.po
  po/uk.po
  po/vi.po
  po/zh_CN.po
  po/zh_HK.po
  po/zh_TW.po
Labels: Translation

#1765 Convert 'Tip of the Day' window to Gtk.Template
  gramps/gui/glade/tipofday.glade
  gramps/gui/tipofday.py
Labels: Code Quality

#1790 Proposed code changes for ProbablyAlive code
  gramps/gen/filters/rules/test/person_rules_test.py
  gramps/gen/lib/date.py
  gramps/gen/lib/eventtype.py
  gramps/gen/utils/alive.py
Labels: enhancement

#1620 Convert images in tree reports to thumbnails for embedding
  gramps/gen/plug/docgen/treedoc.py
Labels: enhancement

#1717 Add mypy static type checker to CI and necessary fixes to the source code
  .github/workflows/gramps-ci.yml
  gramps/cli/clidbman.py
  gramps/gen/const.py
  gramps/gen/datehandler/_datedisplay.py
  gramps/gen/datehandler/_dateparser.py
  gramps/gen/datehandler/_datestrings.py
  gramps/gen/db/dummydb.py
  gramps/gen/db/exceptions.py
  gramps/gen/db/generic.py
  gramps/gen/display/name.py
  gramps/gen/filters/rules/_rule.py
  gramps/gen/lib/eventtype.py
  gramps/gen/lib/grampstype.py
  gramps/gen/lib/test/grampstype_test.py
  gramps/gen/plug/_manager.py
  gramps/gen/plug/_pluginreg.py
  gramps/gen/plug/docbackend/cairobackend.py
  gramps/gen/plug/docbackend/docbackend.py
  gramps/gen/plug/report/_paper.py
  gramps/gen/utils/configmanager.py
  gramps/gen/utils/docgen/csvtab.py
  gramps/gen/utils/test/callback_test.py
  gramps/gen/utils/thumbnails.py
  gramps/gui/dialog.py
  gramps/gui/editors/objectentries.py
  gramps/gui/plug/report/_graphreportdialog.py
  gramps/gui/pluginmanager.py
  gramps/gui/views/listview.py
  gramps/gui/views/pageview.py
  gramps/gui/widgets/fanchart2way.py
  gramps/gui/widgets/fanchartdesc.py
  gramps/gui/widgets/validatedmaskedentry.py
  gramps/plugins/docgen/latexdoc.py
  gramps/plugins/drawreport/ancestortree.py
  gramps/plugins/drawreport/descendtree.py
  gramps/plugins/gramplet/filter.py
  gramps/plugins/lib/libcairodoc.py
  gramps/plugins/lib/libholiday.py
  gramps/plugins/lib/libhtml.py
  gramps/plugins/lib/libhtmlbackend.py
  gramps/plugins/lib/libodfbackend.py
  gramps/plugins/lib/libsubstkeyword.py
  gramps/plugins/lib/maps/__init__.py
  gramps/plugins/lib/maps/geography.py
  gramps/plugins/test/tools_test.py
  gramps/plugins/tool/testcasegenerator.py
  gramps/plugins/webreport/common.py
  gramps/test/regrtest.py
  test/GrampsLogger/ErrorReportAssistant_Test.py
  test/GrampsLogger/GtkHandler_Test.py
Labels: Code Quality

#1857 Improved descend report
  gramps/gen/plug/report/utils.py
  gramps/plugins/textreport/descendreport.py
Labels: enhancement

#1818 Add gender symbol option to the detailed ancestral report
  gramps/plugins/textreport/detancestralreport.py
Labels: enhancement

#1819 Add gender symbol option to the detailed descendant report
  gramps/plugins/textreport/detdescendantreport.py
Labels: enhancement

#1833 Set initial focus in EditPlaceRef dialog
  gramps/gui/editors/editplaceref.py
Labels: enhancement

#1850 Regression: Exception in Redo
  gramps/gen/db/generic.py
Labels: bug

#1832 Improve the backlinks (References) gramplets
  gramps/gui/clipboard.py
  gramps/gui/listmodel.py
  gramps/plugins/gramplet/backlinks.py
Labels: enhancement

#1835 Narweb: languages menu + hamburger menu correction.
  data/css/Web_Basic-Ash.css
  data/css/Web_Basic-Blue.css
  data/css/Web_Basic-Cypress.css
  data/css/Web_Basic-Lilac.css
  data/css/Web_Basic-Peach.css
  data/css/Web_Basic-Spruce.css
  data/css/Web_Mainz.css
  data/css/Web_Nebraska.css
  gramps/plugins/webreport/basepage.py
  gramps/plugins/webreport/multilang.py
Labels: bug, enhancement

#1839 Create DataDict from object; Get object with from_dict()
  gramps/gen/lib/serialize.py
  gramps/gen/lib/test/datadict_test.py
Labels: enhancement, Code Quality

#1842 Remove serialize from changenames
  gramps/gen/db/utils.py
  gramps/plugins/tool/changenames.py
Labels: bug

#1836 Enhancements to Selector Dialogs
  gramps/gui/clipboard.py
  gramps/gui/editors/displaytabs/gallerytab.py
  gramps/gui/selectors/baseselector.py
  gramps/gui/selectors/selectobject.py
  gramps/gui/widgets/multitreeview.py
Labels: enhancement

#1848 Fix AttributeError in editor surname tab
  gramps/gui/editors/displaytabs/surnametab.py
Labels: bug

#1855 Recognize event reference citations in editor event tabs
  gramps/gui/editors/displaytabs/eventrefmodel.py
Labels: bug

#1856 Fix narrative web when a person excluded by a proxy is referenced
  gramps/plugins/webreport/narrativeweb.py
Labels: bug

#1866 Fix python format string related xgettext warnings
  gramps/gui/configure.py
  gramps/plugins/webreport/surnamelist.py
Labels: bug

#1867 Translations update from Hosted Weblate
  po/ar.po
  po/bg.po
  po/br.po
  po/ca.po
  po/cs.po
  po/da.po
  po/de.po
  po/de_AT.po
  po/el.po
  po/en_GB.po
  po/eo.po
  po/es.po
  po/fa.po
  po/fi.po
  po/fr.po
  po/ga.po
  po/gl.po
  po/he.po
  po/hr.po
  po/hu.po
  po/id.po
  po/is.po
  po/it.po
  po/ja.po
  po/ko.po
  po/lt.po
  po/mk.po
  po/nb.po
  po/nl.po
  po/nn.po
  po/pl.po
  po/pt_BR.po
  po/pt_PT.po
  po/ro.po
  po/ru.po
  po/sk.po
  po/sl.po
  po/sq.po
  po/sr.po
  po/sr_Latn.po
  po/sv.po
  po/ta.po
  po/tr.po
  po/uk.po
  po/vi.po
  po/zh_CN.po
  po/zh_HK.po
  po/zh_TW.po
Labels: Translation

#1863 Replace assert statements with TestCase methods in unit tests
  gramps/cli/test/argparser_test.py
  gramps/cli/test/user_test.py
  gramps/gen/lib/test/serialize_test.py
  gramps/gen/test/constfunc_test.py
Labels: Code Quality

#1846 Allow importing and exporting nicknames to CSV
  data/tests/exp_sample_csv.csv
  data/tests/exp_sample_csv.gramps
  data/tests/imp_sample_csv.csv
  data/tests/imp_sample_csv.gramps
  gramps/plugins/export/exportcsv.py
  gramps/plugins/importer/importcsv.py
Labels: enhancement

#1874 Fix exact search filters in selector dialogs
  gramps/gui/selectors/baseselector.py
Labels: bug

#1861 Use orjson, if available
  README.md
  aio/build.sh
  aio/setup.py
  gramps/gen/lib/serialize.py
  gramps/grampsapp.py
  gramps/gui/aboutdialog.py
  gramps/gui/logger/_errorreportassistant.py
  mac/gramps.modules
Labels: enhancement, performance

#1897 Fix "alt_names" typo in the place model
  gramps/gui/views/treemodels/placemodel.py
Labels: bug

#1892 removed unreachable else statement
  gramps/gen/utils/alive.py
Labels: Code Quality, ready-to-merge

#1885 Use ngettext in probably alive function
  gramps/gen/utils/alive.py
Labels: Translation

#1886 Add a translation context to a couple of name origin types
  gramps/gen/lib/nameorigintype.py
Labels: Translation

#1887 The space used as an empty column heading does not need translation
  gramps/plugins/lib/libmetadata.py
Labels: Translation

#1889 Rephrase the citation references option in the narrative web report
  gramps/plugins/webreport/narrativeweb.py
Labels: Translation

#1890 Use ngettext when displaying the max probably alive age in years
  gramps/gen/lib/date.py
Labels: Translation

#1891 Add a preference option for the selection of the toolbar style
  gramps/gen/config.py
  gramps/gui/configure.py
  gramps/gui/uimanager.py
Labels: enhancement

#1865 Add the standard search bar to the SelectPerson dialog
  gramps/gui/editors/editfamily.py
  gramps/gui/selectors/baseselector.py
  gramps/gui/selectors/selectperson.py
Labels: enhancement

#1881 Safe mode working with Gramps 5.2 on Windows
  gramps/gen/const.py
Labels: bug

#1902 Translations update from Hosted Weblate
  po/ar.po
  po/bg.po
  po/br.po
  po/ca.po
  po/cs.po
  po/da.po
  po/de.po
  po/de_AT.po
  po/el.po
  po/en_GB.po
  po/eo.po
  po/es.po
  po/fa.po
  po/fi.po
  po/fr.po
  po/ga.po
  po/gl.po
  po/he.po
  po/hr.po
  po/hu.po
  po/id.po
  po/is.po
  po/it.po
  po/ja.po
  po/ko.po
  po/lt.po
  po/mk.po
  po/nb.po
  po/nl.po
  po/nn.po
  po/pl.po
  po/pt_BR.po
  po/pt_PT.po
  po/ro.po
  po/ru.po
  po/sk.po
  po/sl.po
  po/sq.po
  po/sr.po
  po/sr_Latn.po
  po/sv.po
  po/ta.po
  po/tr.po
  po/uk.po
  po/vi.po
  po/zh_CN.po
  po/zh_HK.po
  po/zh_TW.po
Labels: Translation
