Repository gramps-project/gramps, pull requests merged in 2025-03, with the labels that each got.

#1999 Reformat code using the latest stable version of black
  aio/grampsaiow.py
  aio/setup.py
  gramps/cli/arghandler.py
  gramps/cli/plug/__init__.py
  gramps/cli/test/argparser_test.py
  gramps/cli/test/cli_test.py
  gramps/cli/test/user_test.py
  gramps/gen/db/upgrade.py
  gramps/gen/filters/_filterlist.py
  gramps/gen/filters/rules/place/_withinarea.py
  gramps/gen/lib/__init__.py
  gramps/gen/lib/test/datadict_test.py
  gramps/gen/lib/test/date_test.py
  gramps/gen/lib/test/grampstype_test.py
  gramps/gen/lib/test/merge_test.py
  gramps/gen/lib/test/schema_test.py
  gramps/gen/lib/test/serialize_test.py
  gramps/gen/lib/test/styledtext_test.py
  gramps/gen/merge/__init__.py
  gramps/gen/plug/docbackend/cairobackend.py
  gramps/gen/plug/docbackend/docbackend.py
  gramps/gen/plug/docgen/graphdoc.py
  gramps/gen/plug/docgen/treedoc.py
  gramps/gen/plug/report/_book.py
  gramps/gen/test/config_test.py
  gramps/gen/test/constfunc_test.py
  gramps/gen/utils/test/keyword_test.py
  gramps/gui/ddtargets.py
  gramps/gui/editors/test/editreference_test.py
  gramps/gui/grampsgui.py
  gramps/gui/merge/__init__.py
  gramps/gui/plug/report/_bookdialog.py
  gramps/gui/plug/report/_docreportdialog.py
  gramps/gui/plug/report/_graphreportdialog.py
  gramps/gui/plug/report/_graphvizreportdialog.py
  gramps/gui/plug/report/_reportdialog.py
  gramps/gui/plug/report/_treereportdialog.py
  gramps/gui/selectors/selectnote.py
  gramps/gui/test/display_test.py
  gramps/gui/test/user_test.py
  gramps/gui/test/utils_test.py
  gramps/plugins/db/bsddb/bsddb.py
  gramps/plugins/docgen/cairodoc.py
  gramps/plugins/docgen/gtkprint.py
  gramps/plugins/drawreport/fanchart.py
  gramps/plugins/gramplet/givennamegramplet.py
  gramps/plugins/lib/libcairodoc.py
  gramps/plugins/lib/libgedcom.py
  gramps/plugins/lib/libhtmlbackend.py
  gramps/plugins/lib/libodfbackend.py
  gramps/plugins/lib/librecurse.py
  gramps/plugins/quickview/samesurnames.py
  gramps/plugins/test/imports_test.py
  gramps/plugins/textreport/custombooktext.py
  gramps/plugins/textreport/indivcomplete.py
  gramps/plugins/textreport/recordsreport.py
  gramps/plugins/textreport/simplebooktitle.py
  gramps/plugins/tool/dumpgenderstats.py
  po/test/po_test.py
Labels: Code Quality

#1995 Fix bug with surname rules in Quick Views
  gramps/plugins/quickview/samesurnames.py
Labels: bug

#1997 Always return str from to_string methods
  gramps/gen/lib/json_utils.py
Labels: bug

#1992 Fix upgrades from bsddb
  gramps/gen/db/generic.py
  gramps/gen/db/upgrade.py
  gramps/plugins/db/bsddb/bsddb.py
  gramps/plugins/db/dbapi/dbapi.py
  gramps/plugins/db/dbapi/sqlite.py
Labels: bug

#1948 mypy: Simplify HasSourceOfBase.prepare()
  gramps/gen/filters/rules/_hassourceofbase.py
Labels: Code Quality

#1949 mypy: Simplify RelationshipPathBetween.prepare()
  gramps/gen/filters/rules/person/_relationshippathbetween.py
Labels: Code Quality

#2003 Translations update from Hosted Weblate
  po/eo.po
Labels: Translation

#2007 Fix schema upgrade errors
  gramps/gen/db/generic.py
Labels: bug

#2012 Fix nested transaction error in the Test Case Generator tool
  gramps/plugins/tool/testcasegenerator.py
Labels: bug

#2013 Simplify logic for setting data, config and cache directories
  .github/workflows/gramps-ci.yml
  gramps/gen/config.py
  gramps/gen/const.py
  gramps/grampsapp.py
  gramps/plugins/test/imports_test.py
Labels: bug

#2020 Remove check that path exists in the media path unit test
  gramps/gen/utils/test/file_test.py
Labels: bug

#2023 Add unit tests for the addon translator
  gramps/gen/utils/test/grampslocale_test.py
  gramps/gen/utils/test/locale/fr/LC_MESSAGES/addon.mo
  gramps/gen/utils/test/locale/fr/LC_MESSAGES/addon.po
Labels: Code Quality

#2024 Allow Gramps to continue if an addon rule fails to load
  gramps/gen/plug/_manager.py
Labels: bug

#2025 Translations update from Hosted Weblate
  po/he.po
Labels: Translation

#2015 Add py.typed to indicate the code base is (becoming) typed
  py.typed
Labels: enhancement, Code Quality

#2019 Add mypy configuration
  .github/workflows/gramps-ci.yml
  mypy.ini
Labels: enhancement, Code Quality
