Repository gramps-project/gramps, pull requests merged in 2025-06, with the labels that each got.

#2072 Remove check for Gtk translations in Snap packages
  gramps/gui/grampsgui.py
Labels: Translation

#2052 Refactor Optimizer for correctness
  gramps/gen/filters/__init__.py
  gramps/gen/filters/_filterlist.py
  gramps/gen/filters/_genericfilter.py
  gramps/gen/filters/optimizer.py
  gramps/gen/filters/rules/person/_isdescendantfamilyof.py
  gramps/gen/filters/rules/test/place_rules_test.py
  gramps/gen/filters/test/__init__.py
  gramps/gen/filters/test/filter_optimizer_test.py
  gramps/plugins/test/reports_test.py
  po/POTFILES.skip
Labels: bug

#2057 Respect user choice of CSS files for existing narrated web site
  gramps/plugins/webreport/narrativeweb.py
Labels: bug

#2061 Don't crash if a gramplet fails to load
  gramps/gui/widgets/grampletbar.py
Labels: bug

#2066 Fix crash in Citation View
  gramps/gui/views/listview.py
Labels: bug

#2065 Avoid multiple copies of Rules after Plugin manager reload
  gramps/gen/plug/_manager.py
Labels: bug

#2067 Fix broken compound dates with bce year in XML import
  gramps/plugins/importer/importxml.py
Labels: bug

#2053 Convert to using a `pyproject.toml` based build system
  .github/workflows/gramps-ci.yml
  gramps/gen/const.py
  gramps/gen/filters/rules/test/event_rules_test.py
  gramps/gen/filters/rules/test/family_rules_test.py
  gramps/gen/filters/rules/test/media_rules_test.py
  gramps/gen/filters/rules/test/note_rules_test.py
  gramps/gen/filters/rules/test/person_rules_test.py
  gramps/gen/filters/rules/test/place_rules_test.py
  gramps/gen/filters/rules/test/repository_rules_test.py
  gramps/gen/lib/test/schema_test.py
  gramps/gen/lib/test/serialize_test.py
  gramps/gen/proxy/test/proxies_test.py
  gramps/gen/utils/resourcepath.py
  gramps/grampsapp.py
  gramps/gui/editors/displaytabs/eventembedlist.py
  gramps/gui/editors/displaytabs/personeventembedlist.py
  gramps/plugins/test/exports_test.py
  gramps/plugins/test/imports_test.py
  gramps/plugins/test/reports_test.py
  gramps/plugins/test/tools_test.py
  pyproject.toml
  scripts/build_hook.py
  scripts/version_hook.py
  setup.py
Labels: enhancement

#2063 Dev version correctly reports the SHA of the local HEAD commit
  gramps/gen/const.py
  gramps/gen/git_revision.py
Labels: bug

#2068 Connect the Help button in the repository reference editor
  gramps/gui/editors/editreporef.py
Labels: bug

#2071 Add optimization to has-id rules
  gramps/gen/filters/rules/_hasgrampsid.py
  gramps/gen/filters/rules/citation/_hasidof.py
  gramps/gen/filters/rules/event/_hasidof.py
  gramps/gen/filters/rules/family/_hasidof.py
  gramps/gen/filters/rules/media/_hasidof.py
  gramps/gen/filters/rules/note/_hasidof.py
  gramps/gen/filters/rules/person/_hasidof.py
  gramps/gen/filters/rules/place/_hasidof.py
  gramps/gen/filters/rules/repository/_hasidof.py
  gramps/gen/filters/rules/source/_hasidof.py
Labels: bug
