Repository gramps-project/gramps, pull requests merged in 2025-02, with the labels that each got.

#1894 Fixes to probably alive code following reviewer comments
  gramps/gen/utils/alive.py
Labels: bug

#1904 Remove unnecessary translations
  gramps/plugins/view/relview.py
Labels: Translation

#1903 Correct the tab name for setting the date format in a Tip of the Day
  data/tips.xml
Labels: Translation

#1896 New indexes for big databases in the narrative web report
  data/css/Web_Basic-Ash.css
  data/css/Web_Basic-Blue.css
  data/css/Web_Basic-Cypress.css
  data/css/Web_Basic-Lilac.css
  data/css/Web_Basic-Peach.css
  data/css/Web_Basic-Spruce.css
  data/css/Web_Mainz.css
  data/css/Web_Nebraska.css
  gramps/plugins/webreport/basepage.py
  gramps/plugins/webreport/common.py
  gramps/plugins/webreport/event.py
  gramps/plugins/webreport/family.py
  gramps/plugins/webreport/narrativeweb.py
  gramps/plugins/webreport/person.py
  gramps/plugins/webreport/place.py
  gramps/plugins/webreport/source.py
Labels: enhancement

#1901 Crash with empty ADDR in narrative web
  gramps/plugins/webreport/narrativeweb.py
Labels: bug

#1906 Translations update from Hosted Weblate
  po/ar.po
  po/bg.po
  po/br.po
  po/ca.po
  po/cs.po
  po/da.po
  po/de.po
  po/de_AT.po
  po/el.po
  po/en_GB.po
  po/eo.po
  po/es.po
  po/fa.po
  po/fi.po
  po/fr.po
  po/ga.po
  po/gl.po
  po/he.po
  po/hr.po
  po/hu.po
  po/id.po
  po/is.po
  po/it.po
  po/ja.po
  po/ko.po
  po/lt.po
  po/mk.po
  po/nb.po
  po/nl.po
  po/nn.po
  po/pl.po
  po/pt_BR.po
  po/pt_PT.po
  po/ro.po
  po/ru.po
  po/sk.po
  po/sl.po
  po/sq.po
  po/sr.po
  po/sr_Latn.po
  po/sv.po
  po/ta.po
  po/tr.po
  po/uk.po
  po/vi.po
  po/zh_CN.po
  po/zh_HK.po
  po/zh_TW.po
Labels: Translation

#1898 Use attributes rather than dictionary lookup in the model classes
  gramps/gui/views/treemodels/citationbasemodel.py
  gramps/gui/views/treemodels/citationtreemodel.py
  gramps/gui/views/treemodels/eventmodel.py
  gramps/gui/views/treemodels/familymodel.py
  gramps/gui/views/treemodels/mediamodel.py
  gramps/gui/views/treemodels/notemodel.py
  gramps/gui/views/treemodels/peoplemodel.py
  gramps/gui/views/treemodels/placemodel.py
  gramps/gui/views/treemodels/repomodel.py
  gramps/gui/views/treemodels/sourcemodel.py
Labels: Code Quality

#1899 Add type hints to latitude and longitude methods and functions
  gramps/gen/filters/rules/place/_withinarea.py
  gramps/gen/lib/place.py
  gramps/gen/utils/grampstranslation.py
  gramps/gen/utils/place.py
Labels: Code Quality

#1648 Update help url registrations for built-in reports and tools
  gramps/gui/display.py
  gramps/gui/glade/plugins.glade
  gramps/gui/plug/_dialogs.py
  gramps/gui/test/display_test.py
  gramps/plugins/drawreport/drawplugins.gpr.py
  gramps/plugins/graph/graphplugins.gpr.py
  gramps/plugins/quickview/quickview.gpr.py
  gramps/plugins/textreport/textplugins.gpr.py
  gramps/plugins/tool/tools.gpr.py
  gramps/plugins/tool/toolsdebug.gpr.py
  gramps/plugins/webreport/webplugins.gpr.py
  po/POTFILES.skip
Labels: enhancement

#1900 Report options can memorise options for each database
  gramps/gen/plug/report/_options.py
  gramps/plugins/test/reports_test.py
  gramps/plugins/webreport/narrativeweb.py
Labels: enhancement

#1911 Heatmap for the narrative web.
  gramps/plugins/webreport/basepage.py
  gramps/plugins/webreport/common.py
  gramps/plugins/webreport/heatmap.py
  gramps/plugins/webreport/multiselect.py
  gramps/plugins/webreport/narrativeweb.py
  gramps/plugins/webreport/person.py
  gramps/plugins/webreport/place.py
Labels: enhancement

#1447 Allow web-accessible file references in media objects
  gramps/gen/const.py
  gramps/gen/mime/_pythonmime.py
  gramps/gen/utils/file.py
  gramps/gen/utils/thumbnails.py
  gramps/gui/display.py
  gramps/gui/editors/editmedia.py
  gramps/gui/editors/editmediaref.py
  gramps/gui/utils.py
Labels: enhancement

#1876 Use orjson + encoder
  .github/workflows/gramps-ci.yml
  data/tests/example.gramps
  gramps/gen/db/generic.py
  gramps/gen/db/upgrade.py
  gramps/gen/display/name.py
  gramps/gen/filters/_genericfilter.py
  gramps/gen/filters/rules/test/person_rules_test.py
  gramps/gen/lib/json_utils.py
  gramps/gen/lib/serialize.py
  gramps/gen/lib/test/datadict_test.py
  gramps/gen/lib/test/schema_test.py
  gramps/gen/lib/test/serialize_test.py
  gramps/gen/merge/diff.py
  gramps/gen/proxy/proxybase.py
  gramps/gen/proxy/test/__init__.py
  gramps/gen/proxy/test/proxies_test.py
  gramps/gui/editors/editsecondary.py
  gramps/gui/views/treemodels/citationbasemodel.py
  gramps/gui/views/treemodels/eventmodel.py
  gramps/gui/views/treemodels/mediamodel.py
  gramps/gui/views/treemodels/peoplemodel.py
  gramps/gui/views/treemodels/placemodel.py
  gramps/gui/views/treemodels/repomodel.py
  gramps/plugins/db/dbapi/dbapi.py
  gramps/plugins/gramplet/sessionloggramplet.py
  gramps/plugins/importer/importxml.py
  gramps/plugins/lib/libgedcom.py
  gramps/plugins/lib/libmixin.py
  gramps/plugins/test/imports_test.py
  gramps/plugins/tool/check.py
  gramps/plugins/tool/mediamanager.py
  gramps/plugins/tool/rebuildgenderstat.py
  gramps/plugins/tool/removeunused.py
  po/POTFILES.skip
  test/blob_to_json_test.py
Labels: enhancement, performance

#1916 Define types for Gramps IDs
  gramps/gen/db/generic.py
  gramps/gen/types.py
Labels: Code Quality

#1913 Optimise FilterProxyDb
  gramps/gen/proxy/filter.py
Labels: performance

#1918 Missing future import for annotations
  gramps/gen/lib/json_utils.py
Labels: bug

#1920 Fix accessing an attribute in a DataDict
  gramps/gen/filters/rules/person/_hasnameof.py
  gramps/gen/filters/rules/person/_hassoundexname.py
  gramps/gen/lib/json_utils.py
Labels: bug

#1925 Fix all_people() simple access method to use new data format
  gramps/gen/simple/_simpleaccess.py
Labels: bug

#1926 Enable <Enter> key press on date fields in sidebar filters
  gramps/gui/filters/sidebar/_sidebarfilter.py
Labels: bug

#1927 Fix error when searching by name in the place selector
  gramps/gui/views/treemodels/placemodel.py
Labels: bug

#1933 Translations update from Hosted Weblate
  po/ar.po
  po/bg.po
  po/br.po
  po/ca.po
  po/cs.po
  po/da.po
  po/de.po
  po/de_AT.po
  po/el.po
  po/en_GB.po
  po/eo.po
  po/es.po
  po/fa.po
  po/fi.po
  po/fr.po
  po/ga.po
  po/gl.po
  po/he.po
  po/hr.po
  po/hu.po
  po/id.po
  po/is.po
  po/it.po
  po/ja.po
  po/ko.po
  po/lt.po
  po/mk.po
  po/nb.po
  po/nl.po
  po/nn.po
  po/pl.po
  po/pt_BR.po
  po/pt_PT.po
  po/ro.po
  po/ru.po
  po/sk.po
  po/sl.po
  po/sq.po
  po/sr.po
  po/sr_Latn.po
  po/sv.po
  po/ta.po
  po/tr.po
  po/uk.po
  po/vi.po
  po/zh_CN.po
  po/zh_HK.po
  po/zh_TW.po
Labels: Translation

#1931 Fix the match method in the GenericFilter class
  gramps/gen/filters/_genericfilter.py
Labels: bug

#1928 Added "orjson" and 'all' to setup; updated README
  README.md
  setup.py
Labels: bug

#1939 Fixed a filter/rule that bypasses proxies
  gramps/gen/filters/rules/person/_isdescendantfamilyoffiltermatch.py
Labels: bug

#1940 Correctly handle Event == None in Narrated Web site report
  gramps/plugins/webreport/heatmap.py
Labels: bug

#1941 Private proxy fix
  gramps/gen/proxy/private.py
Labels: bug

#1943 Narrative web: Print page does not show the tree.
  data/css/Web_Print-Default.css
Labels: bug

#1951 Narrative web: crash with empty database.
  gramps/plugins/webreport/common.py
  gramps/plugins/webreport/event.py
  gramps/plugins/webreport/family.py
  gramps/plugins/webreport/person.py
  gramps/plugins/webreport/place.py
  gramps/plugins/webreport/source.py
Labels: bug

#1953 Fix upgrade bug in 6.0
  gramps/gen/lib/serialize.py
  gramps/plugins/db/dbapi/dbapi.py
Labels: bug

#1954 Fixes bsddb upgrade
  gramps/plugins/db/bsddb/bsddb.py
Labels: bug

#1955 Specify the obj_class when calling data_to_object
  gramps/gen/db/generic.py
  gramps/plugins/db/dbapi/dbapi.py
Labels: bug

#1956 Fixes for compatibility with python 3.9
  gramps/gen/filters/rules/family/_isancestorof.py
  gramps/gen/filters/rules/family/_isdescendantof.py
  gramps/gen/filters/rules/person/_deeprelationshippathbetween.py
  gramps/gen/filters/rules/person/_isancestorof.py
  gramps/gen/filters/rules/person/_isdescendantfamilyof.py
  gramps/gen/filters/rules/person/_isdescendantof.py
  gramps/gen/filters/rules/person/_islessthannthgenerationdescendantof.py
  gramps/gen/filters/rules/person/_isrelatedwith.py
Labels: bug

#1958 Change the progress bar vertical alignment and padding
  gramps/gui/widgets/progressdialog.py
Labels: bug

#1959 Rename "Help" button to "Wiki" in plugins dialog
  gramps/gui/glade/plugins.glade
Labels: bug

#1960 Remove BSDDB version and duplicate Gramps version from About dialog
  gramps/gui/aboutdialog.py
Labels: bug

#1964 Fix bug in filter (swapped lines)
  gramps/gen/filters/_genericfilter.py
Labels: bug

#1962 Center the progress bar in the main window status bar
  gramps/gui/widgets/statusbar.py
Labels: bug

#1965 Remote media cannot be opened in the narrativeweb.
  gramps/plugins/webreport/media.py
  gramps/plugins/webreport/thumbnail.py
Labels: bug

#1966 Translations update from Hosted Weblate
  po/de_AT.po
Labels: Translation

#1967 Translations update from Hosted Weblate
  po/ar.po
  po/bg.po
  po/br.po
  po/ca.po
  po/cs.po
  po/da.po
  po/de.po
  po/de_AT.po
  po/el.po
  po/en_GB.po
  po/eo.po
  po/es.po
  po/fa.po
  po/fi.po
  po/fr.po
  po/ga.po
  po/gl.po
  po/he.po
  po/hr.po
  po/hu.po
  po/id.po
  po/is.po
  po/it.po
  po/ja.po
  po/ko.po
  po/lt.po
  po/mk.po
  po/nb.po
  po/nl.po
  po/nn.po
  po/pl.po
  po/pt_BR.po
  po/pt_PT.po
  po/ro.po
  po/ru.po
  po/sk.po
  po/sl.po
  po/sq.po
  po/sr.po
  po/sr_Latn.po
  po/sv.po
  po/ta.po
  po/tr.po
  po/uk.po
  po/vi.po
  po/zh_CN.po
  po/zh_HK.po
  po/zh_TW.po
Labels: Translation

#1970 Convert deprecated filter operator "xor" to its synonym "one"
  gramps/gen/filters/_filterparser.py
Labels: bug

#1972 Fix crash in source/citation selector with an empty filter
  gramps/gui/selectors/baseselector.py
Labels: bug

#1971 Fix citation filter rules that search the source
  gramps/gen/filters/rules/_matchessourcefilterbase.py
  gramps/gen/filters/rules/citation/_hassource.py
  gramps/gen/filters/rules/citation/_hassourceidof.py
  gramps/gen/filters/rules/citation/_hassourcenoteregexp.py
  gramps/gen/filters/rules/citation/_regexpsourceidof.py
Labels: bug

#1976 Translations update from Hosted Weblate
  po/ar.po
  po/bg.po
  po/br.po
  po/ca.po
  po/cs.po
  po/da.po
  po/de.po
  po/de_AT.po
  po/el.po
  po/en_GB.po
  po/eo.po
  po/es.po
  po/fa.po
  po/fi.po
  po/fr.po
  po/ga.po
  po/gl.po
  po/he.po
  po/hr.po
  po/hu.po
  po/id.po
  po/is.po
  po/it.po
  po/ja.po
  po/ko.po
  po/lt.po
  po/mk.po
  po/nb.po
  po/nl.po
  po/nn.po
  po/pl.po
  po/pt_BR.po
  po/pt_PT.po
  po/ro.po
  po/ru.po
  po/sk.po
  po/sl.po
  po/sq.po
  po/sr.po
  po/sr_Latn.po
  po/sv.po
  po/ta.po
  po/tr.po
  po/uk.po
  po/vi.po
  po/zh_CN.po
  po/zh_HK.po
  po/zh_TW.po
Labels: Translation

#1974 Allow older gramps versions to see (not crash) db schema 21
  gramps/gen/db/generic.py
  gramps/gen/db/upgrade.py
  gramps/gen/lib/serialize.py
  gramps/plugins/db/dbapi/dbapi.py
Labels: bug

#1983 Fix media manager bug with relative to absolute path conversion
  gramps/plugins/tool/mediamanager.py
Labels: bug

#1984 Hide navigation bar selector when only one sidebar plugin is loaded
  gramps/gui/navigator.py
Labels: bug

#1985 Add extra checks when changing a parent in the family editor
  gramps/gui/editors/editfamily.py
Labels: bug

#1989 Provide new editor fallback icons for superscript and subscript
  gramps/gui/widgets/styledtexteditor.py
  images/LICENSE
  images/hicolor/scalable/actions/format-text-subscript-symbolic.svg
  images/hicolor/scalable/actions/format-text-superscript-symbolic.svg
Labels: bug

#1991 Strip whitespace from name and URL in Addon Manager project editor
  gramps/gui/plug/_windows.py
Labels: bug

#1994 Strip whitespace from media path in media editor
  gramps/gui/editors/editmedia.py
Labels: bug
