Repository gramps-project/gramps, pull requests merged in 2025-04, with the labels that each got.

#2035 Update the Italian date modifier for "after"
  gramps/gen/datehandler/_date_it.py
Labels: Translation

#2029 Fix issue with empty metadata fields on new databases in Gramps 6.0
  gramps/gen/db/generic.py
Labels: bug

#2030 Fix error when importing a GEDCOM file into an existing tree
  gramps/plugins/lib/libgedcom.py
Labels: bug

#2039 Remove the outer progress meter from the filter prepare phase
  gramps/gen/filters/_genericfilter.py
Labels: bug

#2040 Update Addon Manager wiki Help link from 5.2 to 6.0
  gramps/gui/plug/_windows.py
Labels: bug

#2027 Update the INSTALL file
  INSTALL
Labels: Documentation

#2042 Update links in the README to v6.0
  README.md
Labels: Documentation

#2032 Prevent Unhandled Exception in GuiPersonOption
  gramps/gui/editors/editfamily.py
  gramps/gui/filters/_searchbar.py
  gramps/gui/plug/_guioptions.py
  gramps/gui/selectors/baseselector.py
  gramps/gui/selectors/selectperson.py
  gramps/gui/selectors/selectplace.py
  gramps/gui/views/listview.py
  gramps/gui/views/treemodels/treebasemodel.py
  gramps/plugins/lib/libplaceview.py
  gramps/plugins/view/citationtreeview.py
Labels: bug

#2048 Translations update from Hosted Weblate
  po/ga.po
Labels: Translation
