Repository gramps-project/gramps, pull requests merged in 2025-08, with the labels that each got.

#2085 Fix regression in relationship path between people filter
  gramps/gen/filters/rules/person/_relationshippathbetween.py
Labels: bug

#2089 Apply event place filters to the place not the event
  gramps/gen/filters/rules/event/_matchesplacefilter.py
Labels: bug

#2094 Narrative web: page not found in case we don't want to show sources
  gramps/plugins/webreport/basepage.py
  gramps/plugins/webreport/event.py
  gramps/plugins/webreport/family.py
  gramps/plugins/webreport/person.py
  gramps/plugins/webreport/place.py
Labels: bug

#2096 Fix failure in event filter
  gramps/gen/filters/rules/event/_matchespersonfilter.py
Labels: bug, Approved

#2097 Disambiguate name in glade strings
  gramps/gui/glade/editfamily.glade
  gramps/gui/glade/editplaceformat.glade
  gramps/gui/glade/editplacename.glade
  gramps/gui/glade/editplaceref.glade
  gramps/gui/glade/mergeperson.glade
  gramps/gui/glade/mergeplace.glade
Labels: Translation

#2099 Fixed mixed filter types
  gramps/gen/filters/_genericfilter.py
  gramps/gen/filters/optimizer.py
  gramps/gen/filters/test/filter_optimizer_test.py
Labels: bug, adds-tests

#2102 Fix regex matches in filter match method
  gramps/gen/filters/_genericfilter.py
  gramps/gen/filters/test/filter_optimizer_test.py
Labels: bug, adds-tests
